import Foundation

// ═══════════════════════════════════════════════════════════════
// Strings_de.swift — 🇩🇪 Deutsches Sprachpaket
// ═══════════════════════════════════════════════════════════════

enum Strings_de {
    static let all: [String: String] = [

        // ─── Splash ───────────────────────────────────────────
        "splash.slogan":       "Drive smarter. Grow faster.",

        // ─── Tabs ─────────────────────────────────────────────
        "tab.recording":       "Aufnahme",
        "tab.trips":           "Fahrten",
        "tab.statistics":      "Statistik",
        "tab.settings":        "Einstellungen",

        // ─── Recording View ──────────────────────────────────
        "rec.status.ready":      "BEREIT",
        "rec.status.recording":  "AUFNAHME LÄUFT",
        "rec.status.paused":     "PAUSIERT",
        "rec.metric.km":         "Kilometer",
        "rec.metric.time":       "Fahrzeit",
        "rec.metric.maxspeed":   "Max km/h",
        "rec.gps.searching":     "GPS sucht...",
        "rec.monthly_limit":     "Monatliches Limit",
        "rec.km_remaining":      "%d km übrig",
        "rec.no_profile":        "Kein Fahrzeugprofil",
        "rec.resume":            "Fortsetzen",
        "rec.pause":             "Pause",
        "rec.gps_required":      "GPS-Zugriff benötigt",
        "rec.gps_message":       "Bitte erlaube den Standortzugriff unter Einstellungen → Auto Performance Tracker → Standort → Immer.",
        "rec.open_settings":     "Einstellungen öffnen",

        // ─── Stop Confirm Sheet ──────────────────────────────
        "stop.title":            "Fahrt beenden?",
        "stop.message":          "Die Fahrt wird gespeichert und die\nAufnahme gestoppt.",
        "stop.save":             "Stoppen & Speichern",
        "stop.pause":            "Pausieren",
        "stop.resume":           "Fortsetzen",
        "stop.continue":         "Weiterfahren",

        // ─── Profile Picker ──────────────────────────────────
        "profile.choose":           "Fahrzeug wählen",
        "profile.none_title":       "Keine Fahrzeugprofile",
        "profile.none_message":     "Füge in den Einstellungen ein Fahrzeug hinzu.",
        "profile.close":            "Schließen",

        // ─── Trip List ───────────────────────────────────────
        "trips.title":              "Fahrten",
        "trips.search":             "Fahrt suchen",
        "trips.empty_title":        "Noch keine Fahrten",
        "trips.empty_message":      "Starte deine erste Fahrt im Aufnahme-Tab.",
        "trips.metric.distance":    "Strecke",
        "trips.metric.time":        "Zeit",
        "trips.metric.avgspeed":    "Ø Speed",
        "trips.metric.fuel":        "Sprit",

        // ─── Trip Detail ─────────────────────────────────────
        "detail.distance":          "Strecke",
        "detail.duration":          "Fahrzeit",
        "detail.avg_speed":         "Ø Geschwindigkeit",
        "detail.max_speed":         "Maximalgeschw.",
        "detail.efficiency":        "Effizienz-Score",
        "detail.co2":               "CO₂-Ausstoß",
        "detail.co2_electric":      "0 g (kein Direktausstoß)",
        "detail.cost_per_100km":    "Kosten/100km",
        "detail.fuel_title":        "Spritverbrauch",
        "detail.fuel_estimated":    "Geschätzter Verbrauch",
        "detail.fuel_cost":         "Geschätzte Kosten",
        "detail.fuel_price_at":     "Kraftstoffpreis bei Fahrtende: %@ €/L",
        "detail.analysis":          "Fahrten-Analyse",
        "detail.tips":              "Fahrtipps",
        "detail.done":              "Fertig",
        "detail.pro_title":         "Detaillierte Analyse & Tipps",
        "detail.pro_message":       "Schalte Pro frei für ehrliche Fahrtenanalyse,\nGeschwindigkeitsverteilung und personalisierte Tipps.",
        "detail.pro_unlock":        "Pro freischalten",

        // ─── Statistics View ─────────────────────────────────
        "stats.title":               "Statistik",
        "stats.period.day":          "Tag",
        "stats.period.week":         "Woche",
        "stats.period.month":        "Monat",
        "stats.period.year":         "Jahr",
        "stats.period.total":        "Insgesamt",
        "stats.period.custom":       "Eigener",
        "stats.all_trips":           "Alle Fahrten",
        "stats.total_distance":      "Gesamtstrecke",
        "stats.trip_singular":       "Fahrt",
        "stats.trip_plural":         "Fahrten",
        "stats.from":                "Von",
        "stats.to":                  "Bis",
        "stats.efficiency":          "Driving Score",
        "stats.style_excellent":     "Hervorragender Fahrstil 🌟",
        "stats.style_good":          "Guter Fahrstil ✅",
        "stats.style_aggressive":    "Aggressiver Fahrstil ⚠️",
        "stats.speed_trend":         "GESCHWINDIGKEITSTREND",
        "stats.fuel_per_trip":       "VERBRAUCH PRO FAHRT (L)",
        "stats.fuel_per_trip_diesel":"VERBRAUCH PRO FAHRT - DIESEL (L)",
        "stats.fuel_per_trip_lpg":   "VERBRAUCH PRO FAHRT - LPG (L)",
        "stats.fuel_per_trip_kwh":   "VERBRAUCH PRO FAHRT (kWh)",
        "stats.no_data_period":      "Keine Fahrten im gewählten Zeitraum",
        "stats.no_data":             "Keine auswertbaren Daten",
        "stats.avg_speed":           "Ø Geschwindigkeit",
        "stats.max_speed":           "Maximalgeschw.",
        "stats.total_fuel":          "Gesamtverbrauch",
        "stats.total_fuel_benzin":   "Gesamtverbrauch (Benzin)",
        "stats.total_fuel_diesel":   "Gesamtverbrauch (Diesel)",
        "stats.total_fuel_lpg":      "Gesamtverbrauch (LPG)",
        "stats.total_kwh":           "Gesamtverbrauch (kWh)",
        "stats.total_cost":          "Kosten gesamt",
        "stats.total_time":          "Fahrzeit gesamt",
        "stats.trips_count":         "Fahrten",
        "stats.empty_title":         "Keine Statistiken",
        "stats.empty_message":       "Zeichne Fahrten auf um Statistiken zu sehen.",

        // ─── Settings View ───────────────────────────────────
        "settings.title":             "Einstellungen",
        "settings.pro_banner":        "Auto Performance Tracker Pro",
        "settings.pro_subtitle":      "Unbegrenzt fahren • Analyse • Keine Werbung",
        "settings.vehicles":          "🚗 Fahrzeugprofile",
        "settings.add_vehicle":       "Fahrzeug hinzufügen",
        "settings.more_vehicle_pro":  "Weiteres Fahrzeug (Pro)",
        "settings.vehicle_tip_pro":   "Tippe auf ein Profil um es als Standard zu setzen.",
        "settings.vehicle_tip_std":   "Standard: 1 Fahrzeug. Pro für unbegrenzte Fahrzeuge.",
        "settings.default":           "Standard",
        "settings.account":           "☁️ Account",
        "settings.account_sync":      "Account & Sync",
        "settings.fuel":              "⛽ Kraftstoff",
        "settings.fuel_prices":       "Kraftstoffpreise & Tankstellen",
        "settings.nearby_stations":   "Tankstellen in der Nähe (15 km)",
        "settings.overview":          "📊 Übersicht",
        "settings.total_trips":       "Gesamt Fahrten",
        "settings.total_distance":    "Gesamtstrecke",
        "settings.total_fuel":        "Gesamtsprit",
        "settings.monthly_limit":     "Diesen Monat (Limit)",
        "settings.export":            "📤 Daten exportieren",
        "settings.export_csv":        "Alle Fahrten als CSV",
        "settings.export_json":       "Alle Fahrten als JSON",
        "settings.data_mgmt":         "⚠️ Datenverwaltung",
        "settings.delete_all":        "Alle Fahrten löschen",
        "settings.delete_confirm":    "Alle Fahrten löschen?",
        "settings.delete_message":    "Dieser Schritt kann nicht rückgängig gemacht werden.",
        "settings.delete_action":     "Löschen",
        "settings.privacy_section":   "🔒 Datenschutz",
        "settings.analytics_toggle":  "Anonyme Statistik teilen",
        "settings.crashlytics_toggle": "Absturzberichte senden",
        "settings.crashlytics_note":   "Fehlerberichte an Firebase (Google, USA) – hilft Abstürze zu beheben.",
        "settings.analytics_note":    "Hilft uns die App zu verbessern. Kein GPS, kein Name.",
        "settings.analytics_footer":  "100% anonym, gebucketed, EU-Server. Jederzeit abschaltbar.",
        "settings.info":              "ℹ️ App-Info",
        "settings.version":           "Version",
        "settings.storage":           "Datenspeicherung",
        "settings.storage_local":     "Lokal auf Gerät",
        "settings.sub_status":        "Abo-Status",
        "settings.sub_pro":           "Pro ✓",
        "settings.sub_standard":      "Standard",
        "settings.changelog":         "Changelog / Neuigkeiten",
        "settings.new_badge":         "NEU",
        "settings.appearance":        "Erscheinungsbild",
        "settings.theme.system":      "System",
        "settings.theme.light":       "Hell",
        "settings.theme.dark":        "Dunkel",
        "settings.legal":             "⚖️ Rechtliches & Mehr",
        "settings.privacy":           "Datenschutzerklärung",
        "settings.impressum":         "Impressum",
        "settings.terms":             "AGB",
        "settings.reset_onboarding":  "Einführung erneut anzeigen",
        "settings.restore":           "Käufe wiederherstellen",
        "settings.language":          "🌍 Sprache / Language",
        "settings.language_footer":   "Sprachänderung wird sofort übernommen.",
        "settings.contact":           "✉️ Kontakt & Support",
        "settings.contact_support":   "Support per E-Mail",
        "settings.send_email":        "E-Mail senden",
        "settings.email_subject":     "Frage zur App",
        "settings.support_page":      "Support & FAQ",
        "settings.developer_website": "Entwickler-Website",
        "settings.business_footer":   "",

        // ─── Vehicle Profile Edit ────────────────────────────
        "vehicle.add":               "Fahrzeug hinzufügen",
        "vehicle.edit":              "Fahrzeug bearbeiten",
        "vehicle.name_section":      "Fahrzeugname",
        "vehicle.name_placeholder":  "z.B. VW Golf 8",
        "vehicle.fuel_section":      "Kraftstoff",
        "vehicle.fuel_type":         "Kraftstoffart",
        "vehicle.fuel_gasoline":     "Benzin",
        "vehicle.fuel_diesel":       "Diesel",
        "vehicle.fuel_lpg":          "LPG",
        "vehicle.fuel_electric":     "Elektrisch",
        "vehicle.fuel_hybrid":       "Hybrid",
        "vehicle.consumption_elec":  "Verbrauch (kWh/100km)",
        "vehicle.consumption_fuel":  "Verbrauch (L/100km)",
        "vehicle.fuel_price":        "Kraftstoffpreis (€/L)",
        "vehicle.value":             "Wert",
        "vehicle.price":             "Preis",

        // ─── Common ──────────────────────────────────────────
        "common.ok":                "OK",
        "common.cancel":            "Abbrechen",
        "common.save":              "Speichern",
        "common.close":             "Schließen",
        "common.delete":            "Löschen",
        "common.or":                "oder",
        "common.done":              "Fertig",
        "common.skip":              "Überspringen",
        "common.continue":          "Weiter",
        "common.lets_go":           "Los geht's",
        "common.loading":           "Wird geladen...",
        "common.try_again":         "Erneut versuchen",

        // ─── Age Gate ────────────────────────────────────────
        "agegate.title":         "Altersverifizierung",
        "agegate.subtitle":      "Diese App ist nur für Personen ab 17 Jahren.",
        "agegate.prompt":        "Bitte wähle dein Geburtsjahr:",
        "agegate.confirm":       "Weiter",
        "agegate.blocked.title": "Nutzung nicht möglich",
        "agegate.blocked.body":  "Diese App ist ausschließlich für Personen ab 17 Jahren konzipiert. Du erfüllst die Altersvoraussetzung leider nicht.\n\nBitte lösche die App von deinem Gerät.",
        "agegate.blocked.close": "App schließen",

        // ─── Speed Limit Disclaimer ──────────────────────────
        "speedlimit.disclaimer.title":   "Tempolimit-Anzeige",
        "speedlimit.disclaimer.subtitle": "Wichtiger Hinweis vor der ersten Nutzung",
        "speedlimit.disclaimer.body":    "Die Tempolimit-Anzeige basiert auf OpenStreetMap-Daten und kann unvollständig, veraltet oder fehlerhaft sein.\n\nSie dient ausschließlich als unverbindliche Orientierungshilfe und ersetzt in keinem Fall:\n\n• Offizielle Straßenschilder\n• Eigene Aufmerksamkeit im Straßenverkehr\n• Rechtlich bindende Tempolimits\n\nDu trägst die alleinige Verantwortung für die Einhaltung der geltenden Geschwindigkeitsvorschriften. Verlasse dich niemals ausschließlich auf diese Anzeige.",
        "speedlimit.disclaimer.checkbox": "Ich verstehe, dass die Tempolimit-Anzeige nur eine unverbindliche Schätzung ist. Ich verlasse mich nicht darauf und beachte stets die Straßenschilder.",
        "speedlimit.disclaimer.confirm": "Verstanden & weiter",

        // ─── Disclaimer ─────────────────────────────────────
        "disclaimer.title":          "Wichtiger Hinweis",
        "disclaimer.subtitle":       "Bitte lies und bestätige dies vor der Nutzung",
        "disclaimer.info_only":      "Nur ein Informationswerkzeug",
        "disclaimer.info_only_body": "Diese App dient ausschließlich der nachträglichen Auswertung von Fahrten. Sie ist kein Navigations-, Sicherheits- oder Fahrassistenzsystem.",
        "disclaimer.no_drive":       "Nicht während der Fahrt bedienen",
        "disclaimer.no_drive_body":  "Die App darf vom Fahrer nicht während der Fahrt bedient werden. Du trägst die alleinige Verantwortung für die sichere Teilnahme am Straßenverkehr.",
        "disclaimer.gps_accuracy":   "GPS-Daten können ungenau sein",
        "disclaimer.gps_accuracy_body": "Geschwindigkeit, Strecke und Positionen sind Schätzwerte. Sie dürfen nicht für sicherheitsrelevante Entscheidungen verwendet werden.",
        "disclaimer.estimates":      "Verbrauchswerte sind Schätzungen",
        "disclaimer.estimates_body": "Kraftstoffverbrauch, Kosten und CO₂-Werte sind rechnerische Schätzungen ohne Gewähr auf Richtigkeit.",
        "disclaimer.checkbox":       "Ich habe die Hinweise gelesen und verstanden. Ich akzeptiere, dass die App kein Sicherheitssystem ist und nutze sie auf eigene Verantwortung.",
        "disclaimer.confirm":        "Bestätigen & Weiter",
        "disclaimer.must_accept":    "Bitte bestätige die Hinweise um fortzufahren.",

        // ─── Onboarding ─────────────────────────────────────
        "onboarding.1.title":       "Willkommen bei\nAuto Performance Tracker",
        "onboarding.1.subtitle":    "Dein persönlicher Fahrtassistent. Zeichne jede Fahrt auf und behalte den Überblick über Strecke, Geschwindigkeit und Verbrauch.",
        "onboarding.2.title":       "GPS-Tracking\nin Echtzeit",
        "onboarding.2.subtitle":    "Präzises Tracking mit farbiger Geschwindigkeitsvisualisierung auf der Karte – von ruhigem Stadtverkehr bis zur Autobahn.",
        "onboarding.3.title":       "Detaillierte\nStatistiken",
        "onboarding.3.subtitle":    "Analysiere dein Fahrverhalten, spare Kraftstoff und verbessere deinen Effizienz-Score mit jedem Trip.",
        "onboarding.4.title":       "Spritverbrauch\nim Blick",
        "onboarding.4.subtitle":    "Lege ein Fahrzeugprofil an und erhalte nach jeder Fahrt eine genaue Schätzung für Verbrauch und Kosten.",
        "onboarding.5.title":       "Deine Daten\ngehören dir",
        "onboarding.5.subtitle":    "Deine Daten gehören dir. Lokal gespeichert – optionaler Cloud-Sync und anonyme Analysen nur mit deiner Einwilligung. Free-Version mit Werbung, Pro-Version werbefrei.",

        // ─── Account View ────────────────────────────────────
        "account.title":             "Account",
        "account.tab.login":         "Anmelden",
        "account.tab.register":      "Registrieren",
        "account.headline":          "Auto Performance Tracker",
        "account.subtitle":          "Fahrten geräteübergreifend synchronisieren\nund DSGVO-konform verwalten.",
        "account.email_confirm":     "E-Mail bestätigen",
        "account.email_confirm_msg": "Wir haben dir eine Bestätigungs-E-Mail geschickt. Bitte klicke auf den Link in der E-Mail, um dein Konto zu aktivieren. Die App meldet dich danach automatisch an.",
        "account.resend":            "Nochmal senden",
        "account.login":             "Anmelden",
        "account.create":            "Konto erstellen",
        "account.forgot_pw":         "Passwort vergessen?",
        "account.google":            "Mit Google fortfahren",
        "account.guest":             "Als Gast fortfahren",
        "account.tos":               "Mit der Registrierung bestätigst du, unsere Datenschutzerklärung zur Kenntnis genommen zu haben.",
        "account.reset_pw":          "Passwort zurücksetzen",
        "account.reset_email":       "E-Mail-Adresse",
        "account.reset_action":      "Zurücksetzen",
        "account.reset_msg":         "Wir senden dir einen Reset-Link an deine E-Mail-Adresse.",
        "account.field.name":        "Name",
        "account.field.email":       "E-Mail",
        "account.field.password":    "Passwort",
        "account.field.confirm_pw":  "Passwort bestätigen",
        "account.error.required":    "E-Mail und Passwort erforderlich.",
        "account.error.mismatch":    "Passwörter stimmen nicht überein.",
        "account.error.short_pw":    "Passwort muss mindestens 8 Zeichen lang sein.",
        "account.error.guest_disabled": "Gast-Login deaktiviert. Bitte E-Mail oder Apple nutzen.",
        "account.error.apple_device":   "Apple Sign-In fehlgeschlagen. Bitte gehe zu Einstellungen → [dein Name] → melde dich ab und wieder an.",
        "account.error.apple_generic":  "Apple Sign-In fehlgeschlagen. Bitte versuche es erneut.",
        "account.error.google_vc":      "Google Sign-In konnte nicht gestartet werden. Bitte versuche es erneut.",
        "account.error.email_exists":   "Diese E-Mail-Adresse ist bereits registriert. Bitte melde dich an oder nutze 'Passwort vergessen'.",
        "account.error.invalid_credentials": "E-Mail oder Passwort ist falsch. Falls du dich gerade registriert hast, bitte zuerst die Bestätigungs-E-Mail öffnen.",

        // ─── Anonymous Account ───────────────────────────────
        "anon.title":                "Gastkonto",
        "anon.message":              "Deine Fahrten werden lokal gespeichert. Erstelle ein Konto, um Cloud-Sync und DSGVO-Funktionen zu nutzen.",
        "anon.upgrade":              "Konto erstellen & Daten sichern",
        "anon.upgrade_note":         "Fahrten synchronisieren, DSGVO-Export, keine Datenverluste",
        "anon.sign_out":             "Als Gast abmelden",
        "anon.upgrade_title":        "Gastkonto sichern",
        "anon.upgrade_message":      "Erstelle ein Konto oder melde dich an,\num deine Fahrten zu sichern und zu synchronisieren.",

        // ─── Signed In Account ───────────────────────────────
        "signed.user":               "Nutzer",
        "signed.pro_account":        "Pro Account",
        "signed.my_stats":           "Meine Statistiken",
        "signed.trips":              "Fahrten",
        "signed.total":              "Gesamt",
        "signed.vehicles":           "Fahrzeuge",
        "signed.cloud_sync":         "Cloud-Sync",
        "signed.syncing":            "Synchronisiert…",
        "signed.sync_now":           "Jetzt synchronisieren",
        "signed.trips_count":        "%d Fahrten",
        "signed.gdpr":               "Datenschutz (DSGVO)",
        "signed.export_all":         "Alle meine Daten exportieren",
        "signed.your_rights":        "Deine Rechte",
        "signed.rights_text":        "Du hast das Recht auf Auskunft, Berichtigung, Löschung und Datenübertragbarkeit gemäß DSGVO Art. 15–20.",
        "signed.delete_account":     "Account löschen (30-Tage-Frist)",
        "signed.delete_confirm":     "Account löschen?",
        "signed.delete_message":     "Deine Daten werden nach einer 30-tägigen Frist endgültig gelöscht. Bis dahin kannst du die Löschung widerrufen, indem du dich wieder anmeldest.",
        "signed.delete_request":     "Löschen beantragen",
        "signed.sign_out":           "Abmelden",
        "signed.sign_out_confirm":   "Abmelden?",
        "signed.server_info":        "Deine Daten werden auf EU-Servern (Frankfurt) gespeichert und sind DSGVO-konform verschlüsselt. Supabase ist ISO 27001 zertifiziert.",
        "signed.last_sync":          "Zuletzt synchronisiert: %@",
        "signed.sync_error":         "Fehler: %@",
        "signed.sync_active":        "Wird synchronisiert…",
        "signed.not_synced":         "Noch nicht synchronisiert",

        // ─── Edit Profile ────────────────────────────────────
        "edit.title":                "Profil bearbeiten",
        "edit.avatar_color":         "Avatar-Farbe",
        "edit.change_color":         "Farbe tippen zum Ändern",
        "edit.display_name":         "Anzeigename",
        "edit.name_placeholder":     "Dein Name",
        "edit.email_label":          "E-Mail-Adresse",
        "edit.save_failed":          "Speichern fehlgeschlagen: %@",

        // ─── DSGVO Export ────────────────────────────────────
        "export.ready":              "Daten-Export bereit",
        "export.message":            "Deine gesamten Nutzerdaten wurden zusammengestellt (Profil, Fahrten, Fahrzeuge, Audit-Log).",
        "export.save_json":          "Als JSON speichern / teilen",
        "export.gdpr_note":          "Gemäß DSGVO Art. 20 hast du das Recht, diese Daten auf einen anderen Dienst zu übertragen.",
        "export.nav_title":          "DSGVO-Export",

        // ─── Fuel Price View ─────────────────────────────────
        "fuel.title":                "Kraftstoffpreise",
        "fuel.current_price":        "Aktueller Preis",
        "fuel.empty_title":          "Noch keine Preise erfasst",
        "fuel.empty_message":        "Tippe auf 'Preis speichern' bei einer Tankstelle\noder füge einen Preis manuell hinzu.",
        "fuel.add_manual":           "Preis hinzufügen",
        "fuel.type_section":         "Kraftstoffart",
        "fuel.type_label":           "Typ",
        "fuel.price_section":        "Preis (€/L bzw. €/kWh)",
        "fuel.gasoline":             "Benzin (E5)",
        "fuel.e10":                  "Benzin (E10)",
        "fuel.diesel":               "Diesel",
        "fuel.lpg":                  "Autogas (LPG)",
        "fuel.electricity":          "Strom",

        // ─── Kraftstoff & Tankstellen (unified) ──────────────
        "gas.title":                 "Kraftstoff & Tankstellen",
        "gas.loading":               "Tankstellen werden geladen…",
        "gas.no_stations":           "Keine Tankstellen gefunden",
        "gas.refresh":               "Standort aktualisieren",
        "gas.cheapest":              "Günstigste (E5)",
        "gas.nearest":               "Nächste",
        "gas.open":                  "Offen",
        "gas.closed":                "Geschlossen",
        "gas.error_location":        "Standort konnte nicht ermittelt werden.",
        "gas.error_api_key":         "API-Key fehlt.",
        "gas.error_loading":         "Fehler beim Laden der Tankstellen.",
        "gas.save_price":            "Preis speichern",
        "gas.open_maps":             "Route",
        "gas.maps_choose":           "Navigation öffnen mit",
        "gas.maps_apple":            "Apple Maps",
        "gas.maps_google":           "Google Maps",
        "gas.favorite":              "Favorit",
        "gas.fav_active":            "Favorit-Tankstelle aktiv",
        "gas.fav_remove":            "Entfernen",
        "gas.nearest_lpg":           "Nächste LPG",
        "gas.nearest_ev":            "Nächste Ladestation",
        "gas.lpg_station":           "LPG-Tankstelle",
        "gas.price_unknown":         "Preis unbekannt",
        "gas.ev_unknown_power":      "Leistung unbek.",
        "gas.no_lpg_stations":       "Keine LPG-Tankstellen in der Nähe.\nDaten: OpenStreetMap-Community.",
        "gas.no_lpg_nearby":         "Keine LPG-Tankstelle in 15 km gefunden. Nächste Stationen in weiterer Umgebung:",
        "gas.no_ev_stations":        "Keine Ladestationen gefunden.",
        "gas.ev_key_missing":        "OpenChargeMap-API-Key fehlt.\nKey kostenlos unter openchargemap.org/site/develop/api",
        "gas.adopt_vehicle_price":   "Als Fahrzeugpreis",
        "gas.adopt_vehicle_title":   "Preis übernehmen",
        "gas.adopt_vehicle_desc":    "%.3f €/L (%@) auf Fahrzeugprofil übertragen?",
        "gas.incompatible_fuel":     "Andere Kraftstoffart",

        // Feature 04 – Markenfilter
        "gas.brand_label":           "Marke:",
        "gas.brand_all":             "Alle",
        // Feature 05 – Radius-Selektor
        "gas.radius_label":          "Radius:",
        // Feature 06 – Sortierung
        "gas.sort_price":            "Preis",
        "gas.sort_distance":         "Entfernung",

        // ─── Live Recording ──────────────────────────────────
        "rec.live.clean":            "Saubere Fahrt",
        "rec.live.events":           "%d Manöver",

        // ─── Statistics Score History ─────────────────────────
        "stats.score_history":       "Fahrtpunkte-Verlauf",
        "stats.score_avg":           "Ø %d Pkt.",

        // ─── Statistics New Keys ─────────────────────────────
        "stats.distance_chart":      "GESAMTSTRECKE",
        "stats.from_week_hint":      "Ab Woche verfügbar",
        "stats.all_vehicles":        "Alle Fahrzeuge",

        // ─── Vehicle Color ───────────────────────────────────
        "vehicle.color_section":     "Profilfarbe",
        "vehicle.last_saved_price":  "Letzter gespeicherter Preis: %.3f €/L",
        "vehicle.cheapest_saved":    "Günstigster gespeicherter: %.3f €/L",
        "vehicle.no_prices_saved":   "Noch keine Kraftstoffpreise gespeichert.\nPreise über Kraftstoffpreise → Tankstellen speichern.",
        "vehicle.power_price_label": "Strompreis (€/kWh)",
        "vehicle.power_not_available": "Strompreise sind nicht automatisch abrufbar.\nBitte manuell eingeben (z.B. 0.30 €/kWh).",

        // ─── Changelog ──────────────────────────────────────
        "changelog.title":           "Changelog",
        "changelog.type.new":        "NEU",
        "changelog.type.fix":        "FIX",
        "changelog.type.change":     "ÄNDERUNG",
        "changelog.type.pro":        "PRO",

        // ─── Paywall ────────────────────────────────────────
        "paywall.title":             "Pro freischalten",
        "paywall.headline":          "Auto Performance Tracker Pro",
        "paywall.subtitle":          "Unlimitiert fahren. Besser analysieren.",
        "paywall.limit_hint":        "Du bist auf 250 km/Monat und 1 Fahrzeug begrenzt.",
        "paywall.feature":           "Feature",
        "paywall.standard":          "Standard",
        "paywall.pro":               "Pro",
        "paywall.yearly":            "Jährlich",
        "paywall.monthly":           "Monatlich",
        "paywall.badge_popular":     "BELIEBT",
        "paywall.badge_2months":     "1 Woche gratis testen",
        "paywall.saves_amount":      "%@ gespart",
        "paywall.per_year":          "/ Jahr",
        "paywall.per_month":         "/ Mo",
        "paywall.equiv_per_month":   "nur",
        "paywall.monthly_flexible":  "Flexibel — jederzeit kündbar",
        "paywall.switch_to_yearly":  "↑ Wechseln & sparen",
        "paywall.cta_yearly":        "Jetzt starten — 1 Woche gratis",
        "paywall.cta_monthly":       "Jetzt starten — 1 Woche gratis",
        "paywall.trust_cancel":      "Jederzeit kündbar",
        "paywall.trust_secure":      "Sichere Zahlung",
        "paywall.save_pct":          "SPARE 48%",
        "paywall.yearly_then":       "Dann %@/Jahr",
        "paywall.monthly_cancel":    "Monatlich kündbar",
        "paywall.restore":           "Käufe wiederherstellen",
        "paywall.legal":             "Das Abo verlängert sich automatisch. Kündigung jederzeit in iOS-Einstellungen → Abonnements.",
        "paywall.loading":           "Bitte warten...",
        "paywall.error.purchase":    "Kauf fehlgeschlagen: %@",
        "paywall.error.restore":     "Wiederherstellung fehlgeschlagen.",
        "paywall.pending":           "Kauf wird verarbeitet...",
        "paywall.f_unlimited":       "Unbegrenzte Fahrten",
        "paywall.f_unlimited_n":     "Standard: 250 km/Monat",
        "paywall.f_vehicles":        "Unbegrenzte Fahrzeuge",
        "paywall.f_vehicles_n":      "Standard: 1 Fahrzeug",
        "paywall.f_analysis":        "Effizienz-Score & Analyse",
        "paywall.f_tips":            "Smarte Fahrtipps",
        "paywall.f_fuel":            "Live-Kraftstoffpreise",
        "paywall.f_speed_limit":     "Geschwindigkeitsbegrenzung",
        "paywall.f_no_ads":          "Keine Werbung",
        "paywall.f_stats":           "Basis-Statistiken",
        "paywall.f_gps":             "GPS-Tracking & Export",

        // ─── Analytics Consent ──────────────────────────────
        "consent.title":             "Helfe uns die App zu verbessern",
        "consent.p1":                "Vollständig anonym — kein GPS, kein Name, keine Route",
        "consent.p2":                "Nur Bereiche: z.B. '10–50 km Fahrt' (kein exakter Wert)",
        "consent.p3":                "Daten auf EU-Server (Frankfurt) — kein Transfer in USA",
        "consent.p4":                "Jederzeit abschaltbar in Einstellungen → Datenschutz",
        "consent.accept":            "Ja, anonym helfen",
        "consent.decline":           "Nein, danke",

        // ─── Speed Labels ───────────────────────────────────
        "speed.city":                "Stadt",
        "speed.local":               "Ortsverkehr",
        "speed.country":             "Landstraße",
        "speed.express":             "Schnellstraße",
        "speed.highway":             "Autobahn+",

        // ─── Tip Categories ─────────────────────────────────
        "tip.cat.speed":             "Geschwindigkeit",
        "tip.cat.fuel":              "Verbrauch",
        "tip.cat.eco":               "Umwelt",
        "tip.cat.safety":            "Sicherheit",
        "tip.cat.comfort":           "Fahrkomfort",
        "tip.cat.short":             "Kurzstrecke",
        // DrivingTipsEngine v2 — Kategorie-Keys
        "tip.cat.braking":           "Bremsen",
        "tip.cat.acceleration":      "Beschleunigung",
        "tip.cat.cornering":         "Kurven",
        "tip.cat.consistency":       "Konsistenz",
        "tip.cat.efficiency":        "Effizienz",
        "tip.cat.timeofday":         "Tageszeit",
        "tip.impact.high":           "Hoch",
        "tip.impact.medium":         "Mittel",
        "tip.impact.low":            "Niedrig",
        // Smart Tips UI
        "detail.smart_tips":         "Intelligente Fahrtipps",
        "tip.gain_possible":         "bis +%d Pkt.",
        "tip.potential_next":        "Nächste Fahrt: ~%d Pkt.",

        // ─── Driving Tips ───────────────────────────────────
        "tip.spd_01":   "Auf der Autobahn verbrauchst du bei 120 km/h bis zu 25% weniger als bei 150 km/h. Das spart auch Reifen und Bremsen.",
        "tip.spd_02":   "Du hast diese Fahrt mit über 150 km/h begonnen — das kostet nicht nur mehr Sprit, sondern erhöht auch den Bremsweg erheblich.",
        "tip.spd_03":   "Gleichmäßiges Tempo ist der Schlüssel. Wer konstant fährt, spart bis zu 15% Kraftstoff gegenüber wechselndem Gasgeben.",
        "tip.spd_04":   "Vorausschauendes Fahren bedeutet: Ampeln früh beobachten und rollen lassen, statt hart zu bremsen.",
        "tip.fuel_01":  "Dein Verbrauch liegt über 12 L/100km. Überprüfe den Reifendruck — schon 0.3 Bar zu wenig erhöhen den Verbrauch um 3%.",
        "tip.fuel_02":  "Bei diesem Fahrprofil lohnt es sich, im höchstmöglichen Gang zu fahren. Motor-Drehzahl unter 2.000 U/min ist ideal.",
        "tip.fuel_03":  "Klimaanlage auf Stufe 1–2 statt maximaler Kühlung kann bis zu 1 L/100km sparen — besonders im Stadtverkehr.",
        "tip.fuel_04":  "Motor-Stopp-Start: Bei Ampeln über 10 Sekunden lohnt sich Abschalten. Moderne Motoren starten in 0,3 Sekunden.",
        "tip.fuel_05":  "Unnötiger Ballast kostet Sprit. 100 kg Mehrgewicht erhöhen den Verbrauch um ca. 0.6 L/100km.",
        "tip.eco_01":   "Diese Kurzstrecke erzeugt überproportional viele Emissionen — ein kalter Motor stößt bis zu 5× mehr aus als betriebswarmer.",
        "tip.eco_02":   "Fahrten unter 5 km sind für Motorräder besonders schädlich. Für diese Strecken wäre ein E-Bike oder Gehen eine echte Alternative.",
        "tip.eco_03":   "Du bist diese Fahrt besonders umweltfreundlich gefahren. So viel CO₂ hast du eingespart wie eine Stunde E-Bike-Fahrt einspart.",
        "tip.eco_04":   "Schaltpunkt-Anzeigen beachten: Wer bei niedrigen Drehzahlen schaltet, spart Sprit und schont den Motor.",
        "tip.saf_01":   "Abrupte Brems- und Beschleunigungsmanöver wurden erkannt. Das erhöht das Unfallrisiko — besonders bei Nässe.",
        "tip.saf_02":   "Sehr hohe Maximalgeschwindigkeit: Bei Tempo 160 brauchst du doppelt so langen Bremsweg wie bei Tempo 130.",
        "tip.saf_03":   "Sicherheitsabstand: Bei 130 km/h sind das 65 Meter Mindestabstand (halber Tacho-Wert in Metern).",
        "tip.saf_04":   "Viel Stadtverkehr erkannt. Besonders aufmerksam bei Fußgängerüberwegen und Radfahrern — 90% der Unfälle passieren in 50-Zonen.",
        "tip.com_01":   "Sehr gleichmäßige Fahrt — hervorragend für Fahrgäste und Rücken. Weiter so!",
        "tip.com_02":   "Bei häufigen Stopps: Bremsflüssigkeit regelmäßig prüfen — sie verliert bei starker Beanspruchung ihre Wirkung.",
        "tip.com_03":   "Reifendruck alle 2 Wochen prüfen: Richtiger Druck verbessert Handling und Komfort spürbar.",
        "tip.top_01":   "Hervorragender Fahrstil! 🌟 Du fährst konstant, sparsam und sicher. Das ist echtes Profi-Niveau.",
        "tip.top_02":   "Guter Fahrstil ✅ — kleines Verbesserungspotenzial liegt im gleichmäßigeren Tempo.",
        "tip.hwy_01":   "Autobahnanteil erkannt: Tempomat/Abstandsregeltempomat nutzen — spart durchschnittlich 8% Sprit.",
        "tip.hwy_02":   "Auf der Autobahn gilt: Im 6. Gang mit 120 km/h verbrauchst du fast halb so viel wie im 4. Gang mit 100 km/h.",
        "tip.short":    "Fahrt zu kurz für detaillierte Analyse. Mehr Daten ab 500m Strecke.",

        // ─── Smart Tip Format-Strings (tip.f.*) — enthalten Platzhalter für echte Fahrtdaten ──
        // BREMSEN
        "tip.f.brake_multi":         "%d Vollbremsungen auf %.1f km — eine alle %.1f km. Frühzeitig vom Gas nehmen senkt das auf null.",
        "tip.f.brake_few":           "%d harte Bremsung(en) erkannt. Etwas mehr Sicherheitsabstand würde bereits reichen.",
        "tip.f.brake_avg":           "Ø Bremsverzögerung %.1f m/s² — über dem Komfortwert (2.0). Sanfteres Entschleunigen schont Beläge und Passagiere.",
        "tip.f.brake_excellent":     "0 harte Bremsungen auf %.1f km — vorbildlicher Bremsstil. Score %d bestätigt das.",
        // BESCHLEUNIGUNG
        "tip.f.accel_multi":         "%d hartes Anfahren auf %.1f km. Unter 1.5 m/s² beschleunigen spart Kraftstoff, Kupplung und Getriebe.",
        "tip.f.accel_few":           "%d hartes Anfahren erkannt. Sanft anlassen (<1.5 m/s²) bringt sofort einen Effizienz-Gewinn.",
        "tip.f.accel_excellent":     "Kein hartes Anfahren auf dieser Fahrt — Beschleunigungsstil exzellent. Score %d spricht für sich.",
        // GESCHWINDIGKEIT
        "tip.f.speed_limit":         "%.0f %% der Messzeit im Tempolimit. Speed-Score %d — etwas mehr Antizipation bringt bis zu +%d Pkt.",
        "tip.f.speed_high":          "Maximalgeschwindigkeit %d km/h. Bei 130 km/h statt %d sparst du auf langen Strecken ~%d %% Kraftstoff.",
        "tip.f.speed_variance":      "Tempounregelmäßigkeit σ=%.0f km/h — sehr wechselhaft. Gleichmäßigeres Fahren spart 10–15 %% Sprit.",
        "tip.f.speed_excellent":     "Speed-Score %d — gleichmäßiges, limitkonformes Fahren. Sehr gut!",
        // KURVENVERHALTEN
        "tip.f.corner_multi":        "%d hastige Kurve(n) (>0.4g Querbeschleunigung). 15 km/h früher reduzieren schont Reifen und verbessert den Score.",
        "tip.f.corner_single":       "1 hastiger Kurvenwechsel erkannt. Etwas mehr Antizipation vor der Kurve wäre genug.",
        // KONSISTENZ
        "tip.f.consistency_low":     "Längste Strecke ohne Manöver: %.1f km — Ziel: %.1f km. Mehr Vorausschau im Verkehrsfluss hilft hier.",
        "tip.f.consistency_med":     "Konsistenz-Score %d. %.1f km sauber gefahren — noch etwas Luft nach oben.",
        // EFFIZIENZ
        "tip.f.fuel_high":           "%.1f L/100km auf dieser Fahrt. Sanfteres Beschleunigen und Vorausschau beim Bremsen könnte ~1.5 L/100km einsparen.",
        "tip.f.fuel_medium":         "%.1f L/100km — akzeptabel. Frühes Hochschalten bei <2000 U/min spart weiter Kraftstoff.",
        "tip.f.short_trip":          "%.1f km Kurzfahrt: Kalter Motor stößt bis zu 5× mehr Schadstoffe aus als betriebswarmer. Für <3 km lohnt das Fahrrad.",
        "tip.f.fuel_excellent":      "%.1f L/100km — exzellenter Verbrauch! Effizienz-Score %d: Strecke und Verbrauch optimal ausbalanciert.",
        // AUTOBAHN
        "tip.f.highway_cruise":      "%.0f %% Autobahnanteil erkannt. Tempomat bei %d km/h spart ~8 %% Kraftstoff und reduziert Ermüdung.",
        // TAGESZEIT
        "tip.f.night_heavy":         "%.0f %% Nachtfahrtanteil — Zeitfaktor %.2f. Erhöhter Abstand und reduzierte Geschwindigkeit zahlen sich hier besonders aus.",
        "tip.f.rush_hour":           "%.0f %% Stoßzeit erkannt. Mehr Sicherheitsabstand verhindert die unnötigen Bremsmanöver im dichten Verkehr.",
        // GLOBAL POSITIV
        "tip.f.overall_top":         "Score %d: Gleichmäßig, sparsam, sicher — das ist echtes Profi-Niveau. 🌟",
        "tip.f.overall_good":        "Score %d — sehr guter Fahrstil! Stärkster Hebel für noch mehr Punkte: %@.",

        // ─── Statistics Summary ─────────────────────────────
        "summary.under30":       "🏙 %d%% der Fahrt unter 30 km/h (Stadtverkehr / Stopps)",
        "summary.30to50":        "🔵 %d%% zwischen 30–50 km/h (Ortsverkehr)",
        "summary.50to80":        "🟡 %d%% zwischen 50–80 km/h (Landstraße)",
        "summary.80to130":       "🟠 %d%% zwischen 80–130 km/h (Schnellstraße)",
        "summary.over130":       "🔴 %d%% über 130 km/h (Autobahn+)",
        "summary.speed":         "📊 Ø Geschwindigkeit in Bewegung: %d km/h | Max: %d km/h",
        "summary.efficiency":    "⛽ Effizienz: %.1f L/100km (geschätzt)",
        "summary.no_data":       "Zu wenig Datenpunkte für Analyse.",

        // ─── Trip Default Title ─────────────────────────────
        "trip.default_title":    "Fahrt %@",

        // ─── Privacy View ───────────────────────────────────
        "privacy.title":         "Datenschutzerklärung",
        "privacy.updated":       "Zuletzt aktualisiert: Februar 2026",
        "privacy.loading":       "Datenschutzerklärung lädt...",
        "privacy.no_internet":   "Keine Internetverbindung. Zeige gespeicherte Version.",

        // ─── Impressum View ──────────────────────────────────
        "impressum.nav_title":   "Impressum",
        "impressum.loading":     "Impressum lädt...",

        // ─── Account Legal Links ─────────────────────────────
        "account.privacy_link":  "Datenschutzerklärung",
        "account.impressum_link":"Impressum",

        // ─── Avatar Colors ──────────────────────────────────
        "color.cyan":            "Cyan",
        "color.blue":            "Blau",
        "color.purple":          "Lila",
        "color.pink":            "Pink",
        "color.orange":          "Orange",
        "color.green":           "Grün",
        "color.yellow":          "Gelb",
        "color.red":             "Rot",

        // ─── Privacy View (full content) ────────────────────
        "privacy.nav_title":     "Datenschutz",
        "privacy.header_title":  "Datenschutzerklärung",
        "privacy.header_updated":"Zuletzt aktualisiert: Februar 2026",
        "privacy.header_intro":  "Diese Datenschutzerklärung informiert dich über die Art, den Umfang und den Zweck der Verarbeitung personenbezogener Daten innerhalb der App Auto Performance Tracker.",
        "privacy.s1_title":      "1. Verantwortlicher",
        "privacy.s1_content":    "Verantwortlicher im Sinne der DSGVO:\\nAnton Melnychuk\\nHeppenheimer Strasse 39\\n64658 Furth im Odenwald\\nDeutschland\\n\\nKontakt: support@melnychuk-anton.de\\nAntwortzeit: innerhalb von 72 Stunden.\\\\n\\\\nDu hast das Recht, dich mit einer Beschwerde an die zuständige Datenschutz-Aufsichtsbehörde zu wenden (Art. 77 DSGVO). Für Deutschland: Landesbeauftragte(r) für Datenschutz des jeweiligen Bundeslandes.",
        "privacy.s2_title":      "2. Standortdaten",
        "privacy.s2_content":    "Die App erfasst GPS-Standortdaten (Breitengrad, Längengrad, Höhe, Geschwindigkeit, Kurs) ausschließlich während einer aktiven Fahrtaufzeichnung.\n\n• Zweck: Berechnung von Strecke, Geschwindigkeit, Routenverlauf\n• Speicherort (lokal): Standardmäßig nur auf deinem Gerät (On-Device)\n• Speicherort (Cloud, optional): Bei erstelltem Konto + aktiviertem Cloud-Sync werden GPS-Trackpunkte verschlüsselt auf EU-Servern (Supabase, Frankfurt) gespeichert\n• Löschung: Jederzeit über Einstellungen → \"Alle Fahrten löschen\" (löscht auch Cloud-Daten bei aktivem Konto)\n\nRechtsgrundlage: Art. 6 Abs. 1 lit. a DSGVO (Einwilligung via Standortberechtigung; Cloud-Sync zusätzlich Art. 6 Abs. 1 lit. b DSGVO)",
        "privacy.s3_title":      "3. Datenspeicherung & Cloud-Sync",
        "privacy.s3_content":    "Fahrtdaten werden über SwiftData lokal gespeichert.\n\niCloud-Backup (automatisch, falls aktiviert):\n• Unterliegt Apples eigener Datenschutzerklärung\n• Kein Zugang durch den App-Entwickler\n• Deaktivierbar in iOS-Einstellungen\n\nSupabase Cloud-Sync (optional, nur bei registriertem Konto):\n• Anbieter: Supabase Inc., USA; Serverstandort: EU (Frankfurt, AWS eu-central-1)\n• Übertragene Daten: Fahrtdaten inkl. GPS-Punkte, Fahrzeugprofile, Nutzerprofil (E-Mail, Anzeigename)\n• Zweck: Geräteübergreifende Synchronisation\n• Rechtsgrundlage: Art. 6 Abs. 1 lit. b DSGVO\n• Löschung: Konto → „Account löschen\" entfernt alle Cloud-Daten\n• Datenschutz Supabase: https://supabase.com/privacy\\n\\nDSGVO-Audit-Log: Die App protokolliert datenschutzrelevante Aktionen (Anmeldung, Abmeldung, Einwilligungserteilung) verschlüsselt bei Supabase. Zweck: Nachweis der Rechtmäßigkeit (Art. 5 Abs. 2 DSGVO). Löschung: bei Account-Löschung.\\n• Kaufhistorie/Abo-Status (StoreKit 2): lokal verarbeitet von Apple. Der Entwickler erhält nur den verifizierten Pro-Status, keine Zahlungsdaten.",
        "privacy.s4_title":      "4. Analysedaten (optional, Opt-In)",
        "privacy.s4_content":    "Analytics ist standardmäßig deaktiviert. Du kannst anonyme Nutzungsanalytik freiwillig einschalten (Einstellungen → Datenschutz).\n\nBei aktiviertem Analytics:\n• Anbieter: PostHog Inc., San Francisco, USA; Serverstandort: EU (eu.posthog.com)\n• Übertragene Daten: Vollständig anonymisiert & gebucketed (z.B. Distanzbereich „10–50 km\") – keine GPS-Daten, keine Nutzer-ID, keine Gerätekennungen\n• Zweck: Verbesserung der App-Funktionen\n• Rechtsgrundlage: Art. 6 Abs. 1 lit. a DSGVO (Einwilligung)\n• Widerruf: Jederzeit in Einstellungen → Datenschutz → Analytics deaktivieren\n• Datenschutz PostHog: https://posthog.com/privacy",
        "privacy.s5_title":      "5. Fahrzeugprofile",
        "privacy.s5_content":    "Fahrzeugprofile (Name, Kraftstoffart, Verbrauchswert, Kraftstoffpreis) werden ausschließlich lokal auf deinem Gerät gespeichert. Sie dienen ausschließlich der Berechnung des geschätzten Kraftstoffverbrauchs und werden nicht weitergegeben.",
        "privacy.s6_title":      "6. Datenexport",
        "privacy.s6_content":    "Die App bietet eine Exportfunktion (CSV, JSON). Exportierte Dateien verbleiben in deiner Kontrolle. Mit dem Teilen exportierter Dateien über iOS-Mechanismen (AirDrop, Mail, etc.) giltst du als verantwortliche Person für die weitere Verarbeitung.",
        "privacy.s7_title":      "7. Deine Rechte (DSGVO)",
        "privacy.s7_content":    "Du hast folgende Rechte bezüglich deiner Daten:\n\n• Recht auf Auskunft (Art. 15 DSGVO)\n• Recht auf Berichtigung (Art. 16 DSGVO)\n• Recht auf Löschung (Art. 17 DSGVO) – jederzeit über die App\n• Recht auf Einschränkung der Verarbeitung (Art. 18 DSGVO)\n• Recht auf Datenübertragbarkeit (Art. 20 DSGVO) – via Export-Funktion\n• Recht auf Widerspruch (Art. 21 DSGVO)\n\nLokale Daten löschst du über: Einstellungen → Datenverwaltung → Alle Fahrten löschen. Cloud-Daten werden bei Account-Löschung (Konto → Account löschen) vollständig entfernt.",
        "privacy.s8_title":      "8. Datensicherheit",
        "privacy.s8_content":    "Lokale Daten liegen im geschützten App-Container von iOS. Dritte haben ohne deine explizite Zustimmung keinen Zugriff.\n\nBei Cloud-Sync werden Daten TLS-verschlüsselt übertragen und verschlüsselt auf EU-Servern gespeichert. Supabase ist ISO 27001 zertifiziert. PostHog-Analytics (bei Opt-In) überträgt nur anonymisierte, gebucketete Daten auf EU-Servern.\n\nAdMob (Werbung für Gratis-Nutzer) kann Gerätedaten an Google (USA) übermitteln. Pro-Abonnenten erhalten keine Werbung.",
        "privacy.s9_title":      "9. Minderjährige",
        "privacy.s9_content":    "Die App richtet sich an Nutzer ab 17 Jahren (entsprechend der App-Store-Altersfreigabe). Es werden bewusst keine Daten von Minderjährigen erhoben.",
        "privacy.s10_title":     "10. Änderungen dieser Erklärung",
        "privacy.s10_content":   "Wir behalten uns vor, diese Datenschutzerklärung bei App-Updates anzupassen. Das Datum der letzten Änderung ist stets oben angegeben. Die jeweils aktuelle Fassung ist in der App unter Einstellungen abrufbar.",
        "privacy.s11_title":     "11. Werbung (Google AdMob)",
        "privacy.s11_content":   "Die kostenlose Version der App zeigt Werbeanzeigen über Google AdMob (Google LLC, 1600 Amphitheatre Pkwy, Mountain View, CA 94043, USA).\n\n• Übertragene Daten: Gerätedaten, Werbe-ID (bei Einwilligung via ATT-Dialog), IP-Adresse\n• Serverstandort: USA (unter EU-Standardvertragsklauseln)\n• Zweck: Finanzierung der kostenlosen App-Version\n• Rechtsgrundlage: Art. 6 Abs. 1 lit. a DSGVO (bei personaliserter Werbung mit ATT-Einwilligung) bzw. lit. f (berechtigtes Interesse, nicht-personalisierte Werbung)\n• Pro-Abonnenten sehen keine Werbung\n• Datenschutz Google: https://policies.google.com/privacy",
        "privacy.s12_title":     "12. Absturz-Berichte (Firebase Crashlytics)",
        "privacy.s12_content":   "Die App verwendet Firebase Crashlytics (Google LLC, USA) für technische Fehleranalyse.\\n\\n• Anbieter: Google LLC, Mountain View, CA, USA\\n• Serverstandort: USA (EU-Standardvertragsklauseln gem. Art. 46 Abs. 2 lit. c DSGVO)\\n• Übertragene Daten: Absturz-Stack-Traces, Gerätemodell, iOS-Version, App-Version, Absturz-Zeitstempel. Bei angemeldeten Nutzern zusätzlich: anonymisierte Nutzer-ID (Supabase UUID, kein Klarnamen-Bezug)\\n• Zweck: Erkennung und Behebung technischer Fehler\\n• Rechtsgrundlage: Art. 6 Abs. 1 lit. f DSGVO (berechtigtes Interesse: funktionsfähige, sichere App)\\n• Opt-Out: In der App unter Einstellungen → Datenschutz → Absturzberichte senden deaktivieren\\n• Datenschutz: https://firebase.google.com/support/privacy\\n\\nGoogle Sign-In: Beim Login über Google verarbeitet Google LLC Authentifizierungsdaten (ID-Token). Rechtsgrundlage: Art. 6 Abs. 1 lit. b DSGVO. Datenschutz: https://policies.google.com/privacy",
        "privacy.s13_title":     "13. Speicherdauer",
        "privacy.s13_content":   "• Lokale Fahrtdaten: bis zur manuellen Löschung oder App-Deinstallation\\n• Cloud-Fahrtdaten (Supabase): bis zur Account-Löschung; Soft-Delete-Einträge: automatisch nach 90 Tagen\\n• Nutzerprofil (E-Mail, Name): bis zur Account-Löschung\\n• Analytics (PostHog, bei Opt-In): anonymisiert, 12 Monate\\n• Absturz-Berichte (Crashlytics): 90 Tage (Firebase-Standard)\\n• DSGVO-Audit-Log: wird bei Account-Löschung entfernt\\n• Anon. Geräte-ID (Analytics): bis zur App-Deinstallation\\n\\nNach Account-Löschung werden alle personenbezogenen Cloud-Daten innerhalb von 30 Tagen endgültig gelöscht.",

        "privacy.footer_title":  "Fragen zum Datenschutz?",
        "privacy.footer_text":   "Kontaktiere uns über den Support-Link im App Store. Wir antworten innerhalb von 72 Stunden.\n\nDiese Datenschutzerklärung ist auch online verfügbar:\nhttps://antonmelken.github.io/auto-performance-tracker/datenschutz.html",

        // ─── Changelog Fallback Entries ─────────────────────
        "changelog.fb.pause":         "Pause-Funktion beim Aufnehmen",
        "changelog.fb.fuel_prices":   "Kraftstoffpreise via Tankerkönig",
        "changelog.fb.speed_limit":   "Geschwindigkeitsbegrenzung (VZ 274)",
        "changelog.fb.pro_sub":       "Pro-Abo: Unbegrenzte Fahrten & Analyse",
        "changelog.fb.speedo_fix":    "Tacho zeigt jetzt 220 km/h korrekt",
        "changelog.fb.standby_fix":   "App geht während Fahrt nicht mehr in Standby",
        "changelog.fb.badge_fix":     "Speed-Badge Farben vereinheitlicht",
        "changelog.fb.efficiency":    "Effizienz-Score basiert jetzt auf echten Fahrdaten",
        "changelog.fb.tips_rework":   "Fahrtipps mit detaillierter Analyse überarbeitet",
        "changelog.version_prefix":   "Version",

        // ─── Chart Labels ───────────────────────────────────
        "chart.trip":            "Fahrt",
        "chart.speed":           "Speed",
        "chart.liters":          "Liter",
        "chart.kwh":             "kWh",

        // ─── Misc hardcoded ─────────────────────────────────
        "fuel.manual_source":    "Manuell",
        "fuel.price_placeholder":"Preis",
        "export.filename_gdpr":  "AutoPerformanceTracker_Datenschutzexport.json",

        // ─── Cloud Sync Toggle ──────────────────────────────
        "signed.auto_sync":       "Automatische Synchronisierung",
        "signed.auto_sync_desc":  "Fahrten nach dem Speichern automatisch synchronisieren",

        // ─── Trip Detail: Vehicle Profile ───────────────────
        "detail.no_profile":      "Kein Fahrzeugprofil zugewiesen",
        "detail.change_profile":  "Wechseln",
        "detail.choose_profile":  "Profil wechseln",

        // ─── Driving Score (7 Säulen) ──────────────────────
        "dscore.title":           "Driving Score",
        "dscore.excellent":       "Hervorragender Fahrstil 🌟",
        "dscore.good":            "Guter Fahrstil ✅",
        "dscore.poor":            "Verbesserungspotenzial ⚠️",
        "dscore.limit_active":    "Tempolimit-Analyse aktiv",
        "dscore.breakdown":       "Score-Aufschlüsselung",

        // Pillar names
        "dscore.p.speed":    "Geschwindigkeit",
        "dscore.p.accel":    "Beschleunigung",
        "dscore.p.brake":    "Bremsen",
        "dscore.p.corner":   "Kurvenverhalten",
        "dscore.p.time":     "Zeitpunkt",
        "dscore.p.consist":  "Konsistenz",
        "dscore.p.effic":    "Effizienz",

        // Detail labels
        "dscore.details":       "Score-Details",
        "dscore.d.compliance":  "Tempolimit-Einhaltung",
        "dscore.d.harsh_accel": "Harte Beschleunigungen",
        "dscore.d.harsh_brake": "Harte Bremsungen",
        "dscore.d.harsh_corner":"Harte Kurven",
        "dscore.d.clean_km":    "Längste saubere Strecke",
        "dscore.d.night":       "Nachtfahrt-Anteil",
        "dscore.d.rush":        "Rush-Hour-Anteil",

        // Score-based tips
        "dscore.tip.speed_limit":  "Achte mehr auf die Geschwindigkeitsbegrenzungen – du überschreitest häufig das Limit.",
        "dscore.tip.speed_abs":    "Deine Höchstgeschwindigkeit ist sehr hoch – versuche gleichmäßiger zu fahren.",
        "dscore.tip.accel":        "Beschleunige sanfter – abruptes Gasgeben erhöht Verbrauch und Verschleiß.",
        "dscore.tip.brake":        "Bremse vorausschauender – häufiges Vollbremsen deutet auf zu spätes Reagieren hin.",
        "dscore.tip.corner":       "Nimm Kurven langsamer – hohe Kurvengeschwindigkeit belastet Reifen und Fahrwerk.",
        "dscore.tip.consistency":  "Versuche gleichmäßiger zu fahren – häufige harte Manöver senken deinen Score.",
        "dscore.tip.efficiency":   "Optimiere deine Streckenplanung – Kurzstrecken und hoher Verbrauch senken die Effizienz.",
        "dscore.tip.night":        "Nachtfahrten erhöhen das Unfallrisiko – fahre besonders aufmerksam bei Dunkelheit.",
        "dscore.tip.excellent":    "Hervorragend! Dein Fahrstil ist sicher, sparsam und gleichmäßig. Weiter so! 🌟",

        // Export
        "export.error.title":      "Export fehlgeschlagen",

        // ─── Notifications ───────────────────────────────────────
        "notif.weekly.title":        "Wochenbericht 📊",
        "notif.weekly.good":         "Diese Woche: %d Fahrten, Ø Score %d – sauber gefahren! 🌿",
        "notif.weekly.average":      "Diese Woche: %d Fahrten, Ø Score %d. Noch Luft nach oben! 💪",
        "notif.weekly.poor":         "Score %d diese Woche. Zeit für eine bessere Fahrt! ⚠️",
        "notif.weekly.none":         "Diese Woche noch keine Fahrt – heute starten?",
        "notif.monthly.title":       "Monatsbericht 🗓️",
        "notif.monthly.body":        "Letzter Monat: %d Fahrten · %.1f km · Ø %d Pkt.",
        "notif.yearly.title":        "Jahresbericht 🏆",
        "notif.yearly.body":         "%d: %d Fahrten · %.0f km · Ø Score %d",
        "notif.update.title":        "Update verfügbar 🎉",
        "notif.update.body":         "Neue Features warten auf dich. Schau was neu ist.",
        "notif.engage.day3.title":   "Du wirst vermisst! 🚗",
        "notif.engage.day3.body":    "3 Tage ohne Fahrt – starte jetzt eine Aufnahme.",
        "notif.engage.day7.title":   "Eine Woche Pause? 🏁",
        "notif.engage.day7.body":    "Dein Fahrstil-Score wartet. Lass uns schauen was drin steckt!",
        "notif.engage.day14.title":  "2 Wochen? Wir vermissen dich! 👋",
        "notif.engage.day14.body":   "Einfach kurz eine Probefahrt – es lohnt sich.",
        "notif.driving.title":       "Bist du unterwegs? 🚗",
        "notif.driving.body":        "Fahrt aufnehmen nicht vergessen! Jetzt starten.",
        "notif.posttrip.title":      "Tipp für deine letzte Fahrt 💡",
        "notif.pro.title":           "Mehr aus deinen Fahrten herausholen 🚀",
        "notif.pro.trip5.body":      "Du hast %d Fahrten aufgenommen! Pro freischalten für vollständige Analyse.",
        "notif.pro.paywall.body":    "Vollständiges Fahrtprotokoll freischalten – 1 Woche gratis 🚀",
        "notif.settings.section":    "Benachrichtigungen",
        "notif.settings.toggle":     "Benachrichtigungen aktivieren",
        "notif.settings.toggle_note":"Fahrberichte, Tipps und Erinnerungen",
        "notif.settings.open_ios":   "iOS-Einstellungen öffnen",

        // ─── Sync Fehler ─────────────────────────────────────
        "sync.error.save":           "Lokales Speichern fehlgeschlagen: %@",
        "sync.error.title":          "Synchronisierung fehlgeschlagen",
        "sync.error.message":        "Deine Daten konnten nicht mit der Cloud synchronisiert werden. Bitte prüfe deine Internetverbindung.",
        "sync.error.retry":          "Erneut versuchen",

        // ─── Share Prompts ────────────────────────────────────
        "notif.share.title":         "Ausgezeichnete Fahrt! 🏆",
        "notif.share.body":          "Score %d/100 – magst du das mit anderen teilen?",
        "share.trip.button":         "Fahrt teilen",
        "share.trip.text":           "🚗 Fahrt vom %@\n📍 %.1f km · ⏱ %@\n⭐ Score: %d/100\n📊 Ø %.0f km/h · Max %.0f km/h\n\nAufgezeichnet mit Auto Performance Tracker",
        "share.month.card":          "Starker Monat! Ø %d Pkt. · %.0f km",
        "share.month.button":        "Teilen",
        "share.month.text":          "📊 Mein Fahrmonat:\n%d Fahrten · %.0f km · Ø Score %d/100\n\nAufgezeichnet mit Auto Performance Tracker",
    ]
}
