import Foundation

// ═══════════════════════════════════════════════════════════════
// Strings_de.swift — 🇬🇧 English Language Pack
// ═══════════════════════════════════════════════════════════════

enum Strings_en {
    static let all: [String: String] = [

        // ─── Splash ───────────────────────────────────────────
        "splash.slogan":       "Drive smarter. Grow faster.",

        // ─── Tabs ─────────────────────────────────────────────
        "tab.recording":       "Recording",
        "tab.trips":           "Trips",
        "tab.statistics":      "Statistics",
        "tab.settings":        "Settings",

        // ─── Recording View ──────────────────────────────────
        "rec.status.ready":      "READY",
        "rec.status.recording":  "RECORDING",
        "rec.status.paused":     "PAUSED",
        "rec.metric.km":         "Kilometers",
        "rec.metric.time":       "Duration",
        "rec.metric.maxspeed":   "Max km/h",
        "rec.gps.searching":     "Searching GPS...",
        "rec.monthly_limit":     "Monthly Limit",
        "rec.km_remaining":      "%d km remaining",
        "rec.no_profile":        "No vehicle profile",
        "rec.resume":            "Resume",
        "rec.pause":             "Pause",
        "rec.gps_required":      "GPS Access Required",
        "rec.gps_message":       "Please allow location access in Settings → Auto Performance Tracker → Location → Always.",
        "rec.open_settings":     "Open Settings",

        // ─── Stop Confirm Sheet ──────────────────────────────
        "stop.title":            "End trip?",
        "stop.message":          "The trip will be saved and\nrecording will stop.",
        "stop.save":             "Stop & Save",
        "stop.pause":            "Pause",
        "stop.resume":           "Resume",
        "stop.continue":         "Continue Driving",

        // ─── Profile Picker ──────────────────────────────────
        "profile.choose":           "Choose Vehicle",
        "profile.none_title":       "No Vehicle Profiles",
        "profile.none_message":     "Add a vehicle in Settings.",
        "profile.close":            "Close",

        // ─── Trip List ───────────────────────────────────────
        "trips.title":              "Trips",
        "trips.search":             "Search trips",
        "trips.empty_title":        "No trips yet",
        "trips.empty_message":      "Start your first trip in the Recording tab.",
        "trips.metric.distance":    "Distance",
        "trips.metric.time":        "Time",
        "trips.metric.avgspeed":    "Avg Speed",
        "trips.metric.fuel":        "Fuel",

        // ─── Trip Detail ─────────────────────────────────────
        "detail.distance":          "Distance",
        "detail.duration":          "Duration",
        "detail.avg_speed":         "Avg Speed",
        "detail.max_speed":         "Max Speed",
        "detail.efficiency":        "Efficiency Score",
        "detail.co2":               "CO₂ Emission",
        "detail.co2_electric":      "0 g (no direct emissions)",
        "detail.cost_per_100km":    "Cost/100km",
        "detail.fuel_title":        "Fuel Consumption",
        "detail.fuel_estimated":    "Estimated Consumption",
        "detail.fuel_cost":         "Estimated Cost",
        "detail.fuel_price_at":     "Fuel price at trip end: %@ €/L",
        "detail.analysis":          "Trip Analysis",
        "detail.tips":              "Driving Tips",
        "detail.done":              "Done",
        "detail.pro_title":         "Detailed Analysis & Tips",
        "detail.pro_message":       "Unlock Pro for honest trip analysis,\nspeed distribution, and personalized tips.",
        "detail.pro_unlock":        "Unlock Pro",

        // ─── Statistics View ─────────────────────────────────
        "stats.title":               "Statistics",
        "stats.period.day":          "Day",
        "stats.period.week":         "Week",
        "stats.period.month":        "Month",
        "stats.period.year":         "Year",
        "stats.period.total":        "All Time",
        "stats.period.custom":       "Custom",
        "stats.all_trips":           "All Trips",
        "stats.total_distance":      "Total Distance",
        "stats.trip_singular":       "Trip",
        "stats.trip_plural":         "Trips",
        "stats.from":                "From",
        "stats.to":                  "To",
        "stats.efficiency":          "Driving Score",
        "stats.style_excellent":     "Excellent Driving Style 🌟",
        "stats.style_good":          "Good Driving Style ✅",
        "stats.style_aggressive":    "Aggressive Driving Style ⚠️",
        "stats.speed_trend":         "SPEED TREND",
        "stats.fuel_per_trip":       "FUEL CONSUMPTION PER TRIP (L)",
        "stats.fuel_per_trip_diesel":"FUEL CONSUMPTION PER TRIP - DIESEL (L)",
        "stats.fuel_per_trip_lpg":   "FUEL CONSUMPTION PER TRIP - LPG (L)",
        "stats.fuel_per_trip_kwh":   "ENERGY CONSUMPTION PER TRIP (kWh)",
        "stats.no_data_period":      "No trips in selected period",
        "stats.no_data":             "No data available",
        "stats.avg_speed":           "Avg Speed",
        "stats.max_speed":           "Max Speed",
        "stats.total_fuel":          "Total Fuel",
        "stats.total_fuel_benzin":   "Total Fuel (Gasoline)",
        "stats.total_fuel_diesel":   "Total Fuel (Diesel)",
        "stats.total_fuel_lpg":      "Total Fuel (LPG)",
        "stats.total_kwh":           "Total Energy (kWh)",
        "stats.total_cost":          "Total Cost",
        "stats.total_time":          "Total Time",
        "stats.trips_count":         "Trips",
        "stats.empty_title":         "No Statistics",
        "stats.empty_message":       "Record trips to see statistics.",

        // ─── Settings View ───────────────────────────────────
        "settings.title":             "Settings",
        "settings.pro_banner":        "Auto Performance Tracker Pro",
        "settings.pro_subtitle":      "Unlimited driving • Analysis • No ads",
        "settings.vehicles":          "🚗 Vehicle Profiles",
        "settings.add_vehicle":       "Add Vehicle",
        "settings.more_vehicle_pro":  "More Vehicles (Pro)",
        "settings.vehicle_tip_pro":   "Tap a profile to set it as default.",
        "settings.vehicle_tip_std":   "Standard: 1 vehicle. Pro for unlimited vehicles.",
        "settings.default":           "Default",
        "settings.account":           "☁️ Account",
        "settings.account_sync":      "Account & Sync",
        "settings.fuel":              "⛽ Fuel",
        "settings.fuel_prices":       "Fuel Prices & Stations",
        "settings.nearby_stations":   "Nearby Gas Stations (15 km)",
        "settings.overview":          "📊 Overview",
        "settings.total_trips":       "Total Trips",
        "settings.total_distance":    "Total Distance",
        "settings.total_fuel":        "Total Fuel",
        "settings.monthly_limit":     "This Month (Limit)",
        "settings.export":            "📤 Export Data",
        "settings.export_csv":        "All trips as CSV",
        "settings.export_json":       "All trips as JSON",
        "settings.data_mgmt":         "⚠️ Data Management",
        "settings.delete_all":        "Delete All Trips",
        "settings.delete_confirm":    "Delete all trips?",
        "settings.delete_message":    "This action cannot be undone.",
        "settings.delete_action":     "Delete",
        "settings.privacy_section":   "🔒 Privacy",
        "settings.analytics_toggle":  "Share Anonymous Statistics",
        "settings.crashlytics_toggle": "Send Crash Reports",
        "settings.crashlytics_note":   "Error reports sent to Firebase (Google, USA) – helps fix crashes.",
        "settings.analytics_note":    "Helps us improve the app. No GPS, no name.",
        "settings.analytics_footer":  "100% anonymous, bucketed, EU servers. Can be disabled anytime.",
        "settings.info":              "ℹ️ App Info",
        "settings.version":           "Version",
        "settings.storage":           "Data Storage",
        "settings.storage_local":     "Local on Device",
        "settings.sub_status":        "Subscription",
        "settings.sub_pro":           "Pro ✓",
        "settings.sub_standard":      "Standard",
        "settings.changelog":         "Changelog / What's New",
        "settings.new_badge":         "NEW",
        "settings.appearance":        "Appearance",
        "settings.theme.system":      "System",
        "settings.theme.light":       "Light",
        "settings.theme.dark":        "Dark",
        "settings.legal":             "⚖️ Legal & More",
        "settings.privacy":           "Privacy Policy",
        "settings.impressum":         "Legal Notice (Impressum)",
        "settings.terms":             "Terms & Conditions",
        "settings.reset_onboarding":  "Show Introduction Again",
        "settings.restore":           "Restore Purchases",
        "settings.language":          "🌍 Language",
        "settings.language_footer":   "Language change takes effect immediately.",
        "settings.contact":           "✉️ Contact & Support",
        "settings.contact_support":   "Email Support",
        "settings.send_email":        "Send Email",
        "settings.email_subject":     "App Question",
        "settings.support_page":      "Support & FAQ",
        "settings.developer_website": "Developer Website",
        "settings.business_footer":   "",

        // ─── Vehicle Profile Edit ────────────────────────────
        "vehicle.add":               "Add Vehicle",
        "vehicle.edit":              "Edit Vehicle",
        "vehicle.name_section":      "Vehicle Name",
        "vehicle.name_placeholder":  "e.g. VW Golf 8",
        "vehicle.fuel_section":      "Fuel",
        "vehicle.fuel_type":         "Fuel Type",
        "vehicle.fuel_gasoline":     "Gasoline",
        "vehicle.fuel_diesel":       "Diesel",
        "vehicle.fuel_lpg":          "LPG",
        "vehicle.fuel_electric":     "Electric",
        "vehicle.fuel_hybrid":       "Hybrid",
        "vehicle.consumption_elec":  "Consumption (kWh/100km)",
        "vehicle.consumption_fuel":  "Consumption (L/100km)",
        "vehicle.fuel_price":        "Fuel Price (€/L)",
        "vehicle.value":             "Value",
        "vehicle.price":             "Price",
        "vehicle.color_section":     "Profile Color",
        "vehicle.last_saved_price":  "Last saved price: %.3f €/L",
        "vehicle.cheapest_saved":    "Cheapest saved: %.3f €/L",
        "vehicle.no_prices_saved":   "No fuel prices saved yet.\nSave prices via Fuel Prices → Gas Stations.",
        "vehicle.power_price_label": "Electricity price (€/kWh)",
        "vehicle.power_not_available": "Electricity prices cannot be fetched automatically.\nPlease enter manually (e.g. 0.30 €/kWh).",

        // ─── Common ──────────────────────────────────────────
        "common.ok":                "OK",
        "common.cancel":            "Cancel",
        "common.save":              "Save",
        "common.close":             "Close",
        "common.delete":            "Delete",
        "common.or":                "or",
        "common.done":              "Done",
        "common.skip":              "Skip",
        "common.continue":          "Continue",
        "common.lets_go":           "Let's Go",
        "common.loading":           "Loading...",
        "common.try_again":         "Try Again",

        // ─── Age Gate ────────────────────────────────────────
        "agegate.title":         "Age Verification",
        "agegate.subtitle":      "This app is only for users aged 17 and older.",
        "agegate.prompt":        "Please select your birth year:",
        "agegate.confirm":       "Continue",
        "agegate.blocked.title": "Access Not Permitted",
        "agegate.blocked.body":  "This app is designed exclusively for users aged 17 and older. Unfortunately you do not meet the age requirement.\n\nPlease delete the app from your device.",
        "agegate.blocked.close": "Close App",

        // ─── Speed Limit Disclaimer ──────────────────────────
        "speedlimit.disclaimer.title":   "Speed Limit Display",
        "speedlimit.disclaimer.subtitle": "Important notice before first use",
        "speedlimit.disclaimer.body":    "The speed limit display is based on OpenStreetMap data and may be incomplete, outdated, or incorrect.\n\nIt serves solely as a non-binding orientation aid and does not replace:\n\n• Official road signs\n• Your own attention in road traffic\n• Legally binding speed limits\n\nYou bear sole responsibility for complying with applicable speed regulations. Never rely solely on this display.",
        "speedlimit.disclaimer.checkbox": "I understand that the speed limit display is only a non-binding estimate. I will not rely on it and will always follow road signs.",
        "speedlimit.disclaimer.confirm": "Understood & continue",

        // ─── Disclaimer ─────────────────────────────────────
        "disclaimer.title":          "Important Notice",
        "disclaimer.subtitle":       "Please read and confirm before using the app",
        "disclaimer.info_only":      "Information Tool Only",
        "disclaimer.info_only_body": "This app is solely for reviewing past trips. It is not a navigation, safety, or driver assistance system.",
        "disclaimer.no_drive":       "Do Not Use While Driving",
        "disclaimer.no_drive_body":  "The driver must not operate this app while driving. You are solely responsible for safe participation in road traffic.",
        "disclaimer.gps_accuracy":   "GPS Data May Be Inaccurate",
        "disclaimer.gps_accuracy_body": "Speed, distance, and positions are estimates. They must not be used for safety-critical decisions.",
        "disclaimer.estimates":      "Consumption Values Are Estimates",
        "disclaimer.estimates_body": "Fuel consumption, costs, and CO₂ values are calculated estimates without any guarantee of accuracy.",
        "disclaimer.checkbox":       "I have read and understood the notices. I accept that this app is not a safety system and use it at my own risk.",
        "disclaimer.confirm":        "Confirm & Continue",
        "disclaimer.must_accept":    "Please confirm the notices to continue.",

        // ─── Onboarding ─────────────────────────────────────
        "onboarding.1.title":       "Welcome to\nAuto Performance Tracker",
        "onboarding.1.subtitle":    "Your personal driving assistant. Record every trip and keep track of distance, speed, and fuel consumption.",
        "onboarding.2.title":       "Real-Time\nGPS Tracking",
        "onboarding.2.subtitle":    "Precise tracking with color-coded speed visualization on the map — from calm city traffic to the highway.",
        "onboarding.3.title":       "Detailed\nStatistics",
        "onboarding.3.subtitle":    "Analyze your driving behavior, save fuel, and improve your efficiency score with every trip.",
        "onboarding.4.title":       "Fuel Consumption\nat a Glance",
        "onboarding.4.subtitle":    "Create a vehicle profile and get an accurate estimate of consumption and costs after every trip.",
        "onboarding.5.title":       "Your Data\nBelongs to You",
        "onboarding.5.subtitle":    "Your data belongs to you. Stored locally – optional Cloud Sync and anonymous analytics only with your consent. Free version includes ads; Pro version is ad-free.",

        // ─── Account View ────────────────────────────────────
        "account.title":             "Account",
        "account.tab.login":         "Log In",
        "account.tab.register":      "Register",
        "account.headline":          "Auto Performance Tracker",
        "account.subtitle":          "Sync trips across devices\nand manage data GDPR-compliant.",
        "account.email_confirm":     "Confirm Email",
        "account.email_confirm_msg": "We sent you a confirmation email. Please click the link in the email to activate your account. The app will sign you in automatically.",
        "account.resend":            "Resend",
        "account.login":             "Log In",
        "account.create":            "Create Account",
        "account.forgot_pw":         "Forgot password?",
        "account.google":            "Continue with Google",
        "account.guest":             "Continue as Guest",
        "account.tos":               "By registering you confirm that you have read our Privacy Policy.",
        "account.reset_pw":          "Reset Password",
        "account.reset_email":       "Email Address",
        "account.reset_action":      "Reset",
        "account.reset_msg":         "We'll send a reset link to your email address.",
        "account.field.name":        "Name",
        "account.field.email":       "Email",
        "account.field.password":    "Password",
        "account.field.confirm_pw":  "Confirm Password",
        "account.error.required":    "Email and password are required.",
        "account.error.mismatch":    "Passwords don't match.",
        "account.error.short_pw":    "Password must be at least 8 characters.",
        "account.error.guest_disabled": "Guest login disabled. Please use email or Apple.",
        "account.error.apple_device":   "Apple Sign-In failed. Go to Settings → [your name] → sign out and sign in again.",
        "account.error.apple_generic":  "Apple Sign-In failed. Please try again.",
        "account.error.google_vc":      "Could not start Google Sign-In. Please try again.",
        "account.error.email_exists":   "This email address is already registered. Please sign in or use 'Forgot Password'.",
        "account.error.invalid_credentials": "Email or password is incorrect. If you just registered, please open the confirmation email first.",

        // ─── Anonymous Account ───────────────────────────────
        "anon.title":                "Guest Account",
        "anon.message":              "Your trips are stored locally. Create an account to enable cloud sync and GDPR features.",
        "anon.upgrade":              "Create Account & Secure Data",
        "anon.upgrade_note":         "Sync trips, GDPR export, no data loss",
        "anon.sign_out":             "Sign Out as Guest",
        "anon.upgrade_title":        "Secure Guest Account",
        "anon.upgrade_message":      "Create an account or sign in\nto secure and sync your trips.",

        // ─── Signed In Account ───────────────────────────────
        "signed.user":               "User",
        "signed.pro_account":        "Pro Account",
        "signed.my_stats":           "My Statistics",
        "signed.trips":              "Trips",
        "signed.total":              "Total",
        "signed.vehicles":           "Vehicles",
        "signed.cloud_sync":         "Cloud Sync",
        "signed.syncing":            "Syncing…",
        "signed.sync_now":           "Sync Now",
        "signed.trips_count":        "%d Trips",
        "signed.gdpr":               "Privacy (GDPR)",
        "signed.export_all":         "Export All My Data",
        "signed.your_rights":        "Your Rights",
        "signed.rights_text":        "You have the right to access, rectification, deletion, and data portability under GDPR Art. 15–20.",
        "signed.delete_account":     "Delete Account (30-day grace period)",
        "signed.delete_confirm":     "Delete Account?",
        "signed.delete_message":     "Your data will be permanently deleted after a 30-day grace period. You can cancel the deletion by signing in again.",
        "signed.delete_request":     "Request Deletion",
        "signed.sign_out":           "Sign Out",
        "signed.sign_out_confirm":   "Sign Out?",
        "signed.server_info":        "Your data is stored on EU servers (Frankfurt) and encrypted GDPR-compliant. Supabase is ISO 27001 certified.",
        "signed.last_sync":          "Last synced: %@",
        "signed.sync_error":         "Error: %@",
        "signed.sync_active":        "Syncing…",
        "signed.not_synced":         "Not yet synced",

        // ─── Edit Profile ────────────────────────────────────
        "edit.title":                "Edit Profile",
        "edit.avatar_color":         "Avatar Color",
        "edit.change_color":         "Tap to change color",
        "edit.display_name":         "Display Name",
        "edit.name_placeholder":     "Your Name",
        "edit.email_label":          "Email Address",
        "edit.save_failed":          "Save failed: %@",

        // ─── DSGVO Export ────────────────────────────────────
        "export.ready":              "Data Export Ready",
        "export.message":            "Your complete user data has been compiled (profile, trips, vehicles, audit log).",
        "export.save_json":          "Save / Share as JSON",
        "export.gdpr_note":          "Under GDPR Art. 20, you have the right to transfer this data to another service.",
        "export.nav_title":          "GDPR Export",

        // ─── Fuel Price View ─────────────────────────────────
        "fuel.title":                "Fuel Prices",
        "fuel.current_price":        "Current Price",
        "fuel.empty_title":          "No prices recorded",
        "fuel.empty_message":        "Tap 'Save Price' on a station below,\nor add a price manually.",
        "fuel.add_manual":           "Add Price",
        "fuel.type_section":         "Fuel Type",
        "fuel.type_label":           "Type",
        "fuel.price_section":        "Price (€/L or €/kWh)",
        "fuel.gasoline":             "Gasoline (E5)",
        "fuel.e10":                  "Gasoline (E10)",
        "fuel.diesel":               "Diesel",
        "fuel.lpg":                  "Autogas (LPG)",
        "fuel.electricity":          "Electricity",

        // ─── Fuel & Stations (unified) ────────────────────────
        "gas.title":                 "Fuel & Stations",
        "gas.loading":               "Loading stations…",
        "gas.no_stations":           "No stations found",
        "gas.refresh":               "Refresh Location",
        "gas.cheapest":              "Cheapest (E5)",
        "gas.nearest":               "Nearest",
        "gas.open":                  "Open",
        "gas.closed":                "Closed",
        "gas.error_location":        "Could not determine location.",
        "gas.error_api_key":         "API key missing.",
        "gas.error_loading":         "Error loading gas stations.",
        "gas.save_price":            "Save Price",
        "gas.open_maps":             "Route",
        "gas.maps_choose":           "Open navigation with",
        "gas.maps_apple":            "Apple Maps",
        "gas.maps_google":           "Google Maps",
        "gas.favorite":              "Favorite",
        "gas.fav_active":            "Favorite station active",
        "gas.fav_remove":            "Remove",
        "gas.nearest_lpg":           "Nearest LPG",
        "gas.nearest_ev":            "Nearest Charging",
        "gas.lpg_station":           "LPG Station",
        "gas.price_unknown":         "Price unknown",
        "gas.ev_unknown_power":      "Power unknown",
        "gas.no_lpg_stations":       "No LPG stations nearby.\nData: OpenStreetMap community.",
        "gas.no_lpg_nearby":         "No LPG station found within 15 km. Nearest stations in wider area:",
        "gas.no_ev_stations":        "No charging stations found.",
        "gas.ev_key_missing":        "OpenChargeMap API key missing.\nGet a free key at openchargemap.org/site/develop/api",
        "gas.adopt_vehicle_price":   "Use as vehicle price",
        "gas.adopt_vehicle_title":   "Apply Price",
        "gas.adopt_vehicle_desc":    "Transfer %.3f €/L (%@) to vehicle profile?",
        "gas.incompatible_fuel":     "Different fuel type",

        // Feature 04 – Brand filter
        "gas.brand_label":           "Brand:",
        "gas.brand_all":             "All",
        // Feature 05 – Radius selector
        "gas.radius_label":          "Radius:",
        // Feature 06 – Sort toggle
        "gas.sort_price":            "Price",
        "gas.sort_distance":         "Distance",

        // ─── Live Recording ──────────────────────────────────
        "rec.live.clean":            "Clean driving",
        "rec.live.events":           "%d events",

        // ─── Statistics Score History ─────────────────────────
        "stats.score_history":       "Trip Score History",
        "stats.score_avg":           "Avg %d pts",

        // ─── Statistics New Keys ─────────────────────────────
        "stats.distance_chart":      "TOTAL DISTANCE",
        "stats.from_week_hint":      "Available from Week view",
        "stats.all_vehicles":        "All Vehicles",

        // ─── Changelog ──────────────────────────────────────
        "changelog.title":           "Changelog",
        "changelog.type.new":        "NEW",
        "changelog.type.fix":        "FIX",
        "changelog.type.change":     "CHANGE",
        "changelog.type.pro":        "PRO",

        // ─── Paywall ────────────────────────────────────────
        "paywall.title":             "Unlock Pro",
        "paywall.headline":          "Auto Performance Tracker Pro",
        "paywall.subtitle":          "Drive unlimited. Analyze better.",
        "paywall.limit_hint":        "You're currently limited to 250 km/month and 1 vehicle.",
        "paywall.feature":           "Feature",
        "paywall.standard":          "Standard",
        "paywall.pro":               "Pro",
        "paywall.yearly":            "Yearly",
        "paywall.monthly":           "Monthly",
        "paywall.badge_popular":     "BEST VALUE",
        "paywall.badge_2months":     "1 week free trial",
        "paywall.saves_amount":      "Save %@",
        "paywall.per_year":          "/ year",
        "paywall.per_month":         "/ mo",
        "paywall.equiv_per_month":   "only",
        "paywall.monthly_flexible":  "Flexible — cancel anytime",
        "paywall.switch_to_yearly":  "↑ Switch & save",
        "paywall.cta_yearly":        "Start Now — 1 Week Free",
        "paywall.cta_monthly":       "Start Now — 1 Week Free",
        "paywall.trust_cancel":      "Cancel anytime",
        "paywall.trust_secure":      "Secure payment",
        "paywall.save_pct":          "SAVE 48%",
        "paywall.yearly_then":       "Then %@/year",
        "paywall.monthly_cancel":    "Cancel anytime",
        "paywall.restore":           "Restore Purchases",
        "paywall.legal":             "Subscription renews automatically. Cancel anytime in iOS Settings → Subscriptions.",
        "paywall.loading":           "Please wait...",
        "paywall.error.purchase":    "Purchase failed: %@",
        "paywall.error.restore":     "Restore failed.",
        "paywall.pending":           "Purchase is being processed...",
        "paywall.f_unlimited":       "Unlimited Trips",
        "paywall.f_unlimited_n":     "Standard: 250 km/month",
        "paywall.f_vehicles":        "Unlimited Vehicles",
        "paywall.f_vehicles_n":      "Standard: 1 vehicle",
        "paywall.f_analysis":        "Efficiency Score & Analysis",
        "paywall.f_tips":            "Smart Driving Tips",
        "paywall.f_fuel":            "Live Fuel Prices",
        "paywall.f_speed_limit":     "Speed Limit Display",
        "paywall.f_no_ads":          "No Ads",
        "paywall.f_stats":           "Basic Statistics",
        "paywall.f_gps":             "GPS Tracking & Export",

        // ─── Analytics Consent ──────────────────────────────
        "consent.title":             "Help us improve the app",
        "consent.p1":                "Completely anonymous — no GPS, no name, no route",
        "consent.p2":                "Only ranges: e.g. '10–50 km trip' (no exact values)",
        "consent.p3":                "Data on EU servers (Frankfurt) — no US transfer",
        "consent.p4":                "Can be disabled anytime in Settings → Privacy",
        "consent.accept":            "Yes, help anonymously",
        "consent.decline":           "No, thanks",

        // ─── Speed Labels ───────────────────────────────────
        "speed.city":                "City",
        "speed.local":               "Urban",
        "speed.country":             "Country Road",
        "speed.express":             "Expressway",
        "speed.highway":             "Highway+",

        // ─── Tip Categories ─────────────────────────────────
        "tip.cat.speed":             "Speed",
        "tip.cat.fuel":              "Consumption",
        "tip.cat.eco":               "Environment",
        "tip.cat.safety":            "Safety",
        "tip.cat.comfort":           "Comfort",
        "tip.cat.short":             "Short Trip",
        // DrivingTipsEngine v2 — category keys
        "tip.cat.braking":           "Braking",
        "tip.cat.acceleration":      "Acceleration",
        "tip.cat.cornering":         "Cornering",
        "tip.cat.consistency":       "Consistency",
        "tip.cat.efficiency":        "Efficiency",
        "tip.cat.timeofday":         "Time of Day",
        "tip.impact.high":           "High",
        "tip.impact.medium":         "Medium",
        "tip.impact.low":            "Low",
        // Smart Tips UI
        "detail.smart_tips":         "Smart Driving Tips",
        "tip.gain_possible":         "up to +%d pts",
        "tip.potential_next":        "Next trip: ~%d pts",

        // ─── Driving Tips ───────────────────────────────────
        "tip.spd_01":   "At 120 km/h on the highway you use up to 25% less fuel than at 150 km/h. This also saves tires and brakes.",
        "tip.spd_02":   "You started this trip at over 150 km/h — that costs more fuel and significantly increases braking distance.",
        "tip.spd_03":   "Consistent speed is key. Driving steadily saves up to 15% fuel compared to fluctuating acceleration.",
        "tip.spd_04":   "Anticipatory driving means: watch traffic lights early and coast rather than braking hard.",
        "tip.fuel_01":  "Your consumption exceeds 12 L/100km. Check tire pressure — just 0.3 bar too low increases consumption by 3%.",
        "tip.fuel_02":  "For this driving profile, it pays to drive in the highest possible gear. Engine RPM below 2,000 is ideal.",
        "tip.fuel_03":  "AC on level 1–2 instead of max cooling can save up to 1 L/100km — especially in city traffic.",
        "tip.fuel_04":  "Engine start-stop: At traffic lights longer than 10 seconds, turning off pays off. Modern engines start in 0.3 seconds.",
        "tip.fuel_05":  "Unnecessary weight costs fuel. 100 kg extra increases consumption by about 0.6 L/100km.",
        "tip.eco_01":   "This short trip produces disproportionate emissions — a cold engine emits up to 5× more than one at operating temperature.",
        "tip.eco_02":   "Trips under 5 km are especially harmful for engines. For these distances, an e-bike or walking is a real alternative.",
        "tip.eco_03":   "You drove this trip especially eco-friendly. You saved as much CO₂ as one hour of e-bike riding saves.",
        "tip.eco_04":   "Pay attention to shift indicators: shifting at low RPM saves fuel and protects the engine.",
        "tip.saf_01":   "Abrupt braking and acceleration detected. This increases accident risk — especially in wet conditions.",
        "tip.saf_02":   "Very high top speed: At 160 km/h you need double the braking distance compared to 130 km/h.",
        "tip.saf_03":   "Safe following distance: At 130 km/h that's 65 meters minimum (half your speedometer reading in meters).",
        "tip.saf_04":   "Heavy city traffic detected. Be especially alert at crosswalks and around cyclists — 90% of accidents happen in 50 km/h zones.",
        "tip.com_01":   "Very smooth driving — excellent for passengers and your back. Keep it up!",
        "tip.com_02":   "Frequent stops detected: Check brake fluid regularly — it loses effectiveness under heavy use.",
        "tip.com_03":   "Check tire pressure every 2 weeks: Correct pressure noticeably improves handling and comfort.",
        "tip.top_01":   "Excellent driving style! 🌟 You drive consistently, economically, and safely. True pro level.",
        "tip.top_02":   "Good driving style ✅ — small room for improvement lies in more consistent speed.",
        "tip.hwy_01":   "Highway portion detected: Use cruise control — saves about 8% fuel on average.",
        "tip.hwy_02":   "On the highway: In 6th gear at 120 km/h you use nearly half as much as in 4th gear at 100 km/h.",
        "tip.short":    "Trip too short for detailed analysis. More data available from 500m distance.",

        // ─── Smart Tip Format Strings (tip.f.*) — contain placeholders for real trip data ──
        // BRAKING
        "tip.f.brake_multi":         "%d hard brakes in %.1f km — one every %.1f km. Lifting off the gas earlier reduces this to zero.",
        "tip.f.brake_few":           "%d hard brake(s) detected. A bit more following distance in traffic would be enough.",
        "tip.f.brake_avg":           "Avg braking force %.1f m/s² — above the comfort threshold of 2.0. Gentler deceleration helps passengers and brake pads.",
        "tip.f.brake_excellent":     "0 hard brakes in %.1f km — exemplary braking style. Score %d confirms it.",
        // ACCELERATION
        "tip.f.accel_multi":         "%d hard accelerations in %.1f km. Staying under 1.5 m/s² saves fuel, clutch, and gearbox.",
        "tip.f.accel_few":           "%d hard acceleration(s) detected. Gentle take-off (<1.5 m/s²) brings immediate efficiency gains.",
        "tip.f.accel_excellent":     "No harsh acceleration on this trip — take-off style excellent. Score %d speaks for itself.",
        // SPEED
        "tip.f.speed_limit":         "%.0f%% of the time within speed limit. Speed score %d — a bit more anticipation gives up to +%d pts.",
        "tip.f.speed_high":          "Max speed %d km/h this trip. At 130 km/h instead of %d you save ~%d%% fuel on longer stretches.",
        "tip.f.speed_variance":      "Speed variance σ=%.0f km/h — very unsteady. Consistent speed saves 10–15%% fuel.",
        "tip.f.speed_excellent":     "Speed score %d — consistent, limit-compliant driving. Excellent!",
        // CORNERING
        "tip.f.corner_multi":        "%d aggressive corner(s) (>0.4g lateral force). Slowing down 15 km/h earlier saves tires and improves score.",
        "tip.f.corner_single":       "1 aggressive corner detected. A bit more anticipation before the curve is enough.",
        // CONSISTENCY
        "tip.f.consistency_low":     "Longest clean stretch: %.1f km — target: %.1f km. More forward-looking in traffic flow helps.",
        "tip.f.consistency_med":     "Consistency score %d. %.1f km clean — some room to improve.",
        // EFFICIENCY
        "tip.f.fuel_high":           "%.1f L/100km this trip. Smoother acceleration and anticipatory braking could save ~1.5 L/100km.",
        "tip.f.fuel_medium":         "%.1f L/100km — acceptable. Shifting up earlier at <2000 rpm saves more fuel.",
        "tip.f.short_trip":          "%.1f km short trip: Cold engine emits up to 5× more pollutants than warm. For <3 km, consider cycling.",
        "tip.f.fuel_excellent":      "%.1f L/100km — excellent consumption! Efficiency score %d: distance and fuel usage optimally balanced.",
        // HIGHWAY
        "tip.f.highway_cruise":      "%.0f%% highway portion detected. Cruise control at %d km/h saves ~8%% fuel and reduces fatigue.",
        // TIME OF DAY
        "tip.f.night_heavy":         "%.0f%% night driving — time factor %.2f. Increased following distance and lower speed pay off especially at night.",
        "tip.f.rush_hour":           "%.0f%% rush hour detected. More following distance prevents unnecessary braking in heavy traffic.",
        // GLOBAL POSITIVE
        "tip.f.overall_top":         "Score %d: Consistent, efficient, safe — true pro-level driving. 🌟",
        "tip.f.overall_good":        "Score %d — great driving style! Biggest lever for more points: %@.",

        // ─── Statistics Summary ─────────────────────────────
        "summary.under30":       "🏙 %d%% of trip under 30 km/h (city traffic / stops)",
        "summary.30to50":        "🔵 %d%% between 30–50 km/h (urban traffic)",
        "summary.50to80":        "🟡 %d%% between 50–80 km/h (country road)",
        "summary.80to130":       "🟠 %d%% between 80–130 km/h (expressway)",
        "summary.over130":       "🔴 %d%% over 130 km/h (highway+)",
        "summary.speed":         "📊 Avg speed in motion: %d km/h | Max: %d km/h",
        "summary.efficiency":    "⛽ Efficiency: %.1f L/100km (estimated)",
        "summary.no_data":       "Not enough data points for analysis.",

        // ─── Trip Default Title ─────────────────────────────
        "trip.default_title":    "Trip %@",

        // ─── Privacy View ───────────────────────────────────
        "privacy.title":         "Privacy Policy",
        "privacy.updated":       "Last updated: February 2026",
        "privacy.loading":       "Loading Privacy Policy...",
        "privacy.no_internet":   "No internet connection. Showing cached version.",

        // ─── Impressum View ──────────────────────────────────
        "impressum.nav_title":   "Legal Notice",
        "impressum.loading":     "Loading Legal Notice...",

        // ─── Account Legal Links ─────────────────────────────
        "account.privacy_link":  "Privacy Policy",
        "account.impressum_link":"Legal Notice",

        // ─── Avatar Colors ──────────────────────────────────
        "color.cyan":            "Cyan",
        "color.blue":            "Blue",
        "color.purple":          "Purple",
        "color.pink":            "Pink",
        "color.orange":          "Orange",
        "color.green":           "Green",
        "color.yellow":          "Yellow",
        "color.red":             "Red",

        // ─── Privacy View (full content) ────────────────────
        "privacy.nav_title":     "Privacy",
        "privacy.header_title":  "Privacy Policy",
        "privacy.header_updated":"Last updated: February 2026",
        "privacy.header_intro":  "This privacy policy informs you about the nature, scope, and purpose of personal data processing within the Auto Performance Tracker app.",
        "privacy.s1_title":      "1. Data Controller",
        "privacy.s1_content":    "Data controller within the meaning of the GDPR:\\nAnton Melnychuk\\nHeppenheimer Strasse 39\\n64658 Furth im Odenwald\\nGermany\\n\\nContact: support@melnychuk-anton.de\\nResponse time: within 72 hours.\\\\n\\\\nYou have the right to lodge a complaint with the competent data protection supervisory authority (Art. 77 GDPR). In Germany: the Data Protection Commissioner of your federal state.",
        "privacy.s2_title":      "2. Location Data",
        "privacy.s2_content":    "The app collects GPS location data (latitude, longitude, altitude, speed, heading) exclusively during an active trip recording.\n\n• Purpose: Calculating distance, speed, and route\n• Storage (local): By default, stored only on your device (on-device)\n• Storage (cloud, optional): If you create an account and enable Cloud Sync, GPS track points are encrypted and stored on EU servers (Supabase, Frankfurt)\n• Deletion: Anytime via Settings → \"Delete All Trips\" (also deletes cloud data if account is active)\n\nLegal basis: Art. 6(1)(a) GDPR (consent via location permission; Cloud Sync additionally Art. 6(1)(b) GDPR)",
        "privacy.s3_title":      "3. Data Storage & Cloud Sync",
        "privacy.s3_content":    "Trip data is stored locally using SwiftData.\n\niCloud Backup (automatic, if enabled):\n• Subject to Apple's own privacy policy\n• No access by the app developer\n• Can be disabled in iOS Settings\n\nSupabase Cloud Sync (optional, registered account required):\n• Provider: Supabase Inc., USA; Server location: EU (Frankfurt, AWS eu-central-1)\n• Data transferred: Trip data incl. GPS points, vehicle profiles, user profile (email, display name)\n• Purpose: Cross-device synchronization\n• Legal basis: Art. 6(1)(b) GDPR\n• Deletion: Account → \"Delete Account\" removes all cloud data\n• Supabase Privacy: https://supabase.com/privacy\\n\\nGDPR Audit Log: The app logs privacy-relevant actions (login, logout, consent) securely in Supabase. Purpose: evidence of lawfulness (Art. 5(2) GDPR). Deletion: upon account deletion.\\n• Purchase history/subscription status (StoreKit 2): processed locally by Apple. The developer only receives the verified Pro status, no payment data.",
        "privacy.s4_title":      "4. Analytics Data (Optional, Opt-In)",
        "privacy.s4_content":    "Analytics is disabled by default. You can voluntarily enable anonymous usage analytics (Settings → Privacy).\n\nWhen analytics is enabled:\n• Provider: PostHog Inc., San Francisco, USA; Server location: EU (eu.posthog.com)\n• Data transferred: Fully anonymized and bucketed (e.g. distance range \"10–50 km\") – no GPS data, no user ID, no device identifiers\n• Purpose: Improving app features\n• Legal basis: Art. 6(1)(a) GDPR (consent)\n• Withdrawal: Anytime via Settings → Privacy → Disable Analytics\n• PostHog Privacy: https://posthog.com/privacy",
        "privacy.s5_title":      "5. Vehicle Profiles",
        "privacy.s5_content":    "Vehicle profiles (name, fuel type, consumption value, fuel price) are stored exclusively on your device. They are used solely to estimate fuel consumption and are not shared with anyone.",
        "privacy.s6_title":      "6. Data Export",
        "privacy.s6_content":    "The app offers an export function (CSV, JSON). Exported files remain under your control. By sharing exported files via iOS mechanisms (AirDrop, Mail, etc.), you become the responsible party for further processing.",
        "privacy.s7_title":      "7. Your Rights (GDPR)",
        "privacy.s7_content":    "You have the following rights regarding your data:\n\n• Right of access (Art. 15 GDPR)\n• Right to rectification (Art. 16 GDPR)\n• Right to erasure (Art. 17 GDPR) – anytime via the app\n• Right to restriction of processing (Art. 18 GDPR)\n• Right to data portability (Art. 20 GDPR) – via the export function\n• Right to object (Art. 21 GDPR)\n\nDelete local data via: Settings → Data Management → Delete All Trips. Cloud data is permanently removed when you delete your account (Account → Delete Account).",
        "privacy.s8_title":      "8. Data Security",
        "privacy.s8_content":    "Local data resides in the protected iOS app container. Third parties have no access without your explicit consent.\n\nWhen Cloud Sync is active, data is transferred via TLS encryption and stored encrypted on EU servers. Supabase is ISO 27001 certified. PostHog analytics (if opted in) only transfers anonymized, bucketed data on EU servers.\n\nAdMob (ads for free users) may transmit device data to Google (USA). Pro subscribers see no ads.",
        "privacy.s9_title":      "9. Minors",
        "privacy.s9_content":    "The app is intended for users aged 17 and older (per App Store age rating). No data from minors is intentionally collected.",
        "privacy.s10_title":     "10. Changes to This Policy",
        "privacy.s10_content":   "We reserve the right to update this privacy policy with app updates. The date of the last change is always shown at the top. The current version is available in the app under Settings.",
        "privacy.s11_title":     "11. Advertising (Google AdMob)",
        "privacy.s11_content":   "The free version of the app displays ads via Google AdMob (Google LLC, 1600 Amphitheatre Pkwy, Mountain View, CA 94043, USA).\n\n• Data transferred: Device data, advertising ID (if ATT consent granted), IP address\n• Server location: USA (under EU Standard Contractual Clauses)\n• Purpose: Funding the free version of the app\n• Legal basis: Art. 6(1)(a) GDPR (personalized ads with ATT consent) or Art. 6(1)(f) (legitimate interest, non-personalized ads)\n• Pro subscribers see no ads\n• Google Privacy: https://policies.google.com/privacy",
        "privacy.s12_title":     "12. Crash Reports (Firebase Crashlytics)",
        "privacy.s12_content":   "The app uses Firebase Crashlytics (Google LLC, USA) for technical error analysis.\\n\\n• Provider: Google LLC, Mountain View, CA, USA\\n• Server location: USA (EU Standard Contractual Clauses per Art. 46(2)(c) GDPR)\\n• Data transmitted: crash stack traces, device model, iOS version, app version, crash timestamp. For signed-in users additionally: anonymized user ID (Supabase UUID, no personal name linkage)\\n• Purpose: detecting and fixing technical errors\\n• Legal basis: Art. 6(1)(f) GDPR (legitimate interest: stable, secure app)\\n• Opt-Out: In the app under Settings → Privacy → Send Crash Reports (disable)\\n• Privacy: https://firebase.google.com/support/privacy\\n\\nGoogle Sign-In: When logging in via Google, Google LLC processes authentication data (ID token). Legal basis: Art. 6(1)(b) GDPR. Privacy: https://policies.google.com/privacy",
        "privacy.s13_title":     "13. Data Retention Periods",
        "privacy.s13_content":   "• Local trip data: until manual deletion or app uninstall\\n• Cloud trip data (Supabase): until account deletion; soft-deleted entries: auto-purged after 90 days\\n• User profile (email, name): until account deletion\\n• Analytics (PostHog, if opted in): anonymized, 12 months\\n• Crash reports (Crashlytics): 90 days (Firebase default)\\n• GDPR audit log: removed upon account deletion\\n• Anon. device ID (analytics): until app uninstall\\n\\nAfter account deletion, all personal cloud data is permanently erased within 30 days.",

        "privacy.footer_title":  "Questions about privacy?",
        "privacy.footer_text":   "Contact us via the support link in the App Store. We respond within 72 hours.\n\nThis privacy policy is also available online:\nhttps://antonmelken.github.io/auto-performance-tracker/datenschutz.html",

        // ─── Changelog Fallback Entries ─────────────────────
        "changelog.fb.pause":         "Pause function during recording",
        "changelog.fb.fuel_prices":   "Fuel prices via Tankerkönig",
        "changelog.fb.speed_limit":   "Speed limit display (sign 274)",
        "changelog.fb.pro_sub":       "Pro subscription: Unlimited trips & analysis",
        "changelog.fb.speedo_fix":    "Speedometer now shows 220 km/h correctly",
        "changelog.fb.standby_fix":   "App no longer goes to standby during trips",
        "changelog.fb.badge_fix":     "Speed badge colors unified",
        "changelog.fb.efficiency":    "Efficiency score now based on real driving data",
        "changelog.fb.tips_rework":   "Driving tips with detailed analysis reworked",
        "changelog.version_prefix":   "Version",

        // ─── Chart Labels ───────────────────────────────────
        "chart.trip":            "Trip",
        "chart.speed":           "Speed",
        "chart.liters":          "Liters",
        "chart.kwh":             "kWh",

        // ─── Misc hardcoded ─────────────────────────────────
        "fuel.manual_source":    "Manual",
        "fuel.price_placeholder":"Price",
        "export.filename_gdpr":  "AutoPerformanceTracker_PrivacyExport.json",

        // ─── Cloud Sync Toggle ──────────────────────────────
        "signed.auto_sync":       "Automatic Sync",
        "signed.auto_sync_desc":  "Sync trips automatically after saving",

        // ─── Trip Detail: Vehicle Profile ───────────────────
        "detail.no_profile":      "No vehicle profile assigned",
        "detail.change_profile":  "Change",
        "detail.choose_profile":  "Change Profile",

        // ─── Driving Score (7 Pillars) ──────────────────────
        "dscore.title":           "Driving Score",
        "dscore.excellent":       "Excellent Driving Style 🌟",
        "dscore.good":            "Good Driving Style ✅",
        "dscore.poor":            "Room for Improvement ⚠️",
        "dscore.limit_active":    "Speed limit analysis active",
        "dscore.breakdown":       "Score Breakdown",

        // Pillar names
        "dscore.p.speed":    "Speed",
        "dscore.p.accel":    "Acceleration",
        "dscore.p.brake":    "Braking",
        "dscore.p.corner":   "Cornering",
        "dscore.p.time":     "Time of Day",
        "dscore.p.consist":  "Consistency",
        "dscore.p.effic":    "Efficiency",

        // Detail labels
        "dscore.details":       "Score Details",
        "dscore.d.compliance":  "Speed Limit Compliance",
        "dscore.d.harsh_accel": "Harsh Accelerations",
        "dscore.d.harsh_brake": "Harsh Brakings",
        "dscore.d.harsh_corner":"Harsh Corners",
        "dscore.d.clean_km":    "Longest Clean Distance",
        "dscore.d.night":       "Night Driving Ratio",
        "dscore.d.rush":        "Rush Hour Ratio",

        // Score-based tips
        "dscore.tip.speed_limit":  "Pay more attention to speed limits – you frequently exceed the limit.",
        "dscore.tip.speed_abs":    "Your top speed is very high – try to drive more evenly.",
        "dscore.tip.accel":        "Accelerate more gently – abrupt throttle increases fuel consumption and wear.",
        "dscore.tip.brake":        "Brake more proactively – frequent hard braking suggests late reactions.",
        "dscore.tip.corner":       "Take corners slower – high cornering speeds stress tires and suspension.",
        "dscore.tip.consistency":  "Try to drive more smoothly – frequent harsh maneuvers lower your score.",
        "dscore.tip.efficiency":   "Optimize your route planning – short trips and high consumption reduce efficiency.",
        "dscore.tip.night":        "Night driving increases accident risk – drive especially carefully in the dark.",
        "dscore.tip.excellent":    "Excellent! Your driving style is safe, efficient and smooth. Keep it up! 🌟",

        // Export
        "export.error.title":      "Export Failed",

        // ─── Notifications ───────────────────────────────────────
        "notif.weekly.title":        "Weekly Report 📊",
        "notif.weekly.good":         "This week: %d trips, avg score %d – great driving! 🌿",
        "notif.weekly.average":      "This week: %d trips, avg score %d. Room to improve! 💪",
        "notif.weekly.poor":         "Score %d this week. Time for a better drive! ⚠️",
        "notif.weekly.none":         "No trips this week – start one today?",
        "notif.monthly.title":       "Monthly Report 🗓️",
        "notif.monthly.body":        "Last month: %d trips · %.1f km · avg %d pts",
        "notif.yearly.title":        "Year in Review 🏆",
        "notif.yearly.body":         "%d: %d trips · %.0f km · avg score %d",
        "notif.update.title":        "Update Available 🎉",
        "notif.update.body":         "New features are waiting for you. See what's new.",
        "notif.engage.day3.title":   "We miss you! 🚗",
        "notif.engage.day3.body":    "3 days without a trip – start recording now.",
        "notif.engage.day7.title":   "A week off? 🏁",
        "notif.engage.day7.body":    "Your driving score is waiting. Let's see what you've got!",
        "notif.engage.day14.title":  "2 weeks? We miss you! 👋",
        "notif.engage.day14.body":   "Just a short test drive – it's worth it.",
        "notif.driving.title":       "Are you driving? 🚗",
        "notif.driving.body":        "Don't forget to record your trip! Start now.",
        "notif.posttrip.title":      "Tip for your last trip 💡",
        "notif.pro.title":           "Get more from your trips 🚀",
        "notif.pro.trip5.body":      "You've recorded %d trips! Unlock Pro for full analysis.",
        "notif.pro.paywall.body":    "Unlock your complete trip log – try 1 week free 🚀",
        "notif.settings.section":    "Notifications",
        "notif.settings.toggle":     "Enable Notifications",
        "notif.settings.toggle_note":"Trip reports, tips, and reminders",
        "notif.settings.open_ios":   "Open iOS Settings",

        // ─── Sync Errors ─────────────────────────────────────
        "sync.error.save":           "Local save failed: %@",
        "sync.error.title":          "Sync Failed",
        "sync.error.message":        "Your data could not be synced to the cloud. Please check your internet connection.",
        "sync.error.retry":          "Retry",

        // ─── Share Prompts ────────────────────────────────────
        "notif.share.title":         "Excellent Drive! 🏆",
        "notif.share.body":          "Score %d/100 – want to share it with others?",
        "share.trip.button":         "Share Trip",
        "share.trip.text":           "🚗 Trip on %@\n📍 %.1f km · ⏱ %@\n⭐ Score: %d/100\n📊 Avg %.0f km/h · Max %.0f km/h\n\nRecorded with Auto Performance Tracker",
        "share.month.card":          "Strong month! Avg %d pts · %.0f km",
        "share.month.button":        "Share",
        "share.month.text":          "📊 My driving month:\n%d trips · %.0f km · avg score %d/100\n\nRecorded with Auto Performance Tracker",
    ]
}
